import Link from 'next/link';
export const metadata={title:'Terms of Service — Global FDI Monitor'};
export default function TermsPage() {
  const SECTIONS=[
    {title:'Acceptance',content:'By accessing Global FDI Monitor, you agree to these Terms of Service. If you do not agree, do not use the platform.'},
    {title:'Platform Licence',content:'GFM grants you a non-exclusive, non-transferable licence to use the platform per your subscription tier. You may not redistribute, resell, or share your account credentials.'},
    {title:'FIC Credits',content:'Forecasta Intelligence Credits (FIC) are non-refundable once used. Unused FIC credits expire 12 months after purchase. Annual subscription FIC are allocated at subscription start.'},
    {title:'Data & Content',content:'All intelligence, rankings, signals, and reports generated by GFM are provided for informational purposes only and do not constitute financial, investment, or legal advice.'},
    {title:'Intellectual Property',content:'All platform content, GFR methodology, signal detection models, and reports are the intellectual property of Forecasta Ltd. You may not reproduce or redistribute outputs without written permission.'},
    {title:'Prohibited Use',content:'You may not use the platform to: reverse-engineer our models, scrape data systematically, resell access, or use outputs for any unlawful purpose.'},
    {title:'Subscriptions & Billing',content:'Subscriptions auto-renew unless cancelled 7 days before renewal. Refunds are available within 14 days of purchase for annual plans unused beyond 7 days. Contact billing@fdimonitor.org.'},
    {title:'Limitation of Liability',content:'Forecasta\'s liability is limited to the amount paid in the 12 months preceding any claim. We are not liable for consequential, indirect, or punitive damages.'},
    {title:'Governing Law',content:'These terms are governed by the laws of the United Arab Emirates (Dubai). Disputes shall be resolved by the DIFC Courts.'},
  ];
  return (
    <div className="min-h-screen bg-white">
      <div className="bg-[#0A2540] text-white px-6 py-14">
        <div className="max-w-3xl mx-auto"><h1 className="text-4xl font-black mb-2">Terms of Service</h1><p className="text-blue-200">Last updated: March 2026</p></div>
      </div>
      <div className="max-w-3xl mx-auto px-6 py-12 space-y-8">
        {SECTIONS.map(s=>(
          <div key={s.title}><h2 className="text-xl font-black text-[#0A2540] mb-3">{s.title}</h2><p className="text-slate-600 leading-relaxed">{s.content}</p></div>
        ))}
        <div className="pt-6 border-t border-slate-100">
          <Link href="/contact" className="text-blue-600 font-bold hover:underline">Contact us with legal questions →</Link>
        </div>
      </div>
    </div>
  );
}
