import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

export default function PrivacyPage() {
  const sections = [
    ['Data We Collect','We collect: account information (name, email, organisation), usage data (pages visited, features used, report downloads), and payment information (processed by Stripe, not stored by us). We do not collect personal browsing data beyond platform usage.'],
    ['How We Use Data','Account data is used to manage your subscription and send the weekly Intelligence Brief (with your consent). Usage data improves the platform and personalises your experience. We never sell your data to third parties.'],
    ['AI Processing','Investment signals, GOSA scores, and GFR rankings are generated by our AI agent pipeline using publicly available official government data. Your personal data is not used in AI model training.'],
    ['Data Retention','Account data is retained for the duration of your subscription plus 90 days. Usage logs are retained for 12 months. You may request deletion at any time by contacting info@fdimonitor.org.'],
    ['Third-Party Services','We use: SendGrid (email delivery), Stripe (payments), AWS (infrastructure), Azure (AI/compute). All providers are GDPR-compliant and process data under our instructions only.'],
    ['Your Rights','You have the right to: access your data, correct inaccuracies, request deletion, export your data in machine-readable format, and withdraw consent for marketing communications at any time.'],
    ['Cookies','We use essential cookies for session management and analytics cookies (with consent) to improve the platform. We do not use advertising cookies or track users across third-party sites.'],
    ['Contact','Data Controller: Forecasta FZ-LLC, Dubai, UAE. Data enquiries: info@fdimonitor.org'],
  ];

  return (
    <div style={{minHeight:'100vh',background:'#020c14',fontFamily:"'Inter','Helvetica Neue',sans-serif"}}>
      <NavBar/>
      <div style={{maxWidth:'800px',margin:'0 auto',padding:'48px 24px'}}>
        <div style={{fontSize:'10px',fontWeight:800,color:'rgba(0,255,200,0.5)',letterSpacing:'0.2em',marginBottom:'8px',fontFamily:"'Orbitron','Inter',sans-serif"}}>LEGAL</div>
        <h1 style={{fontSize:'28px',fontWeight:900,color:'#e8f4f8',marginBottom:'6px'}}>Privacy Policy</h1>
        <p style={{fontSize:'13px',color:'rgba(232,244,248,0.4)',marginBottom:'40px'}}>Last updated: March 2026 · GDPR compliant · No data selling</p>
        {sections.map(([title, body]) => (
          <div key={title} style={{marginBottom:'28px',paddingBottom:'28px',borderBottom:'1px solid rgba(255,255,255,0.04)'}}>
            <h2 style={{fontSize:'16px',fontWeight:700,color:'#e8f4f8',marginBottom:'8px'}}>{title}</h2>
            <p style={{fontSize:'13px',color:'rgba(232,244,248,0.55)',lineHeight:1.85}}>{body}</p>
          </div>
        ))}
        <div style={{padding:'16px',background:'rgba(0,255,200,0.04)',borderRadius:'10px',border:'1px solid rgba(0,255,200,0.1)',fontSize:'12px',color:'rgba(232,244,248,0.45)'}}>
          Questions? Contact <a href="mailto:info@fdimonitor.org" style={{color:'#00ffc8',textDecoration:'none'}}>info@fdimonitor.org</a>
        </div>
      </div>
      <Footer/>
    </div>
  );
}
