"""
GLOBAL FDI MONITOR — COMPLETE 215 ECONOMIES DATASET
All World Bank recognised economies with:
  - ISO3, ISO2, name, region, income group
  - GDP (USD billions, 2023)
  - FDI inflows (USD billions, 2023)
  - GFR composite score (Q1 2026)
  - GFR tier + rank
  - All 6 GFR dimensions
  - Population (millions)
  - Internet penetration (%)
  - Primary FDI sectors
"""

ALL_215_ECONOMIES = [
    # ── EAST ASIA & PACIFIC ───────────────────────────────────────────────
    {"iso3":"AUS","iso2":"AU","name":"Australia",           "region":"EAP","income":"HIC","pop_m":26.5, "gdp_b":1688,"fdi_b":59.4,"gfr":82.1,"rank":8, "tier":"FRONTIER","macro":84,"policy":85,"digital":83,"human":76,"infra":82,"sustain":81,"internet_pct":91,"sectors":["J","K","D","B"]},
    {"iso3":"BRN","iso2":"BN","name":"Brunei Darussalam",   "region":"EAP","income":"HIC","pop_m":0.4,  "gdp_b":15,  "fdi_b":1.2,"gfr":58.0,"rank":62,"tier":"MEDIUM",  "macro":71,"policy":60,"digital":62,"human":40,"infra":65,"sustain":42,"internet_pct":97,"sectors":["B","D"]},
    {"iso3":"CHN","iso2":"CN","name":"China",                "region":"EAP","income":"UMIC","pop_m":1412,"gdp_b":17795,"fdi_b":163.0,"gfr":61.8,"rank":45,"tier":"MEDIUM", "macro":74,"policy":55,"digital":72,"human":68,"infra":76,"sustain":48,"internet_pct":74,"sectors":["C","J","D","F"]},
    {"iso3":"FJI","iso2":"FJ","name":"Fiji",                 "region":"EAP","income":"UMIC","pop_m":0.9,  "gdp_b":4.5, "fdi_b":0.3,"gfr":41.0,"rank":128,"tier":"EMERGING","macro":44,"policy":42,"digital":48,"human":38,"infra":40,"sustain":38,"internet_pct":54,"sectors":["Q","H","L"]},
    {"iso3":"HKG","iso2":"HK","name":"Hong Kong SAR",        "region":"EAP","income":"HIC","pop_m":7.4,  "gdp_b":369, "fdi_b":116.4,"gfr":85.2,"rank":6, "tier":"FRONTIER","macro":88,"policy":82,"digital":89,"human":72,"infra":94,"sustain":62,"internet_pct":94,"sectors":["K","J","L","H"]},
    {"iso3":"IDN","iso2":"ID","name":"Indonesia",            "region":"EAP","income":"UMIC","pop_m":274,  "gdp_b":1371,"fdi_b":22.0,"gfr":57.1,"rank":67,"tier":"MEDIUM", "macro":64,"policy":54,"digital":55,"human":58,"infra":58,"sustain":48,"internet_pct":77,"sectors":["C","B","D","H"]},
    {"iso3":"JPN","iso2":"JP","name":"Japan",                "region":"EAP","income":"HIC","pop_m":123,  "gdp_b":4213,"fdi_b":30.5,"gfr":79.3,"rank":12,"tier":"HIGH",   "macro":82,"policy":84,"digital":82,"human":74,"infra":88,"sustain":72,"internet_pct":93,"sectors":["C","J","K","D"]},
    {"iso3":"KHM","iso2":"KH","name":"Cambodia",             "region":"EAP","income":"LMIC","pop_m":17,  "gdp_b":27,  "fdi_b":3.2,"gfr":42.1,"rank":126,"tier":"EMERGING","macro":48,"policy":40,"digital":38,"human":34,"infra":42,"sustain":38,"internet_pct":54,"sectors":["C","H","Q"]},
    {"iso3":"KIR","iso2":"KI","name":"Kiribati",             "region":"EAP","income":"LMIC","pop_m":0.1,  "gdp_b":0.2, "fdi_b":0.0,"gfr":22.0,"rank":208,"tier":"DEVELOPING","macro":24,"policy":20,"digital":18,"human":24,"infra":20,"sustain":28,"internet_pct":20,"sectors":["Q"]},
    {"iso3":"KOR","iso2":"KR","name":"Korea, Rep.",          "region":"EAP","income":"HIC","pop_m":52,   "gdp_b":1710,"fdi_b":18.4,"gfr":77.8,"rank":14,"tier":"HIGH",   "macro":80,"policy":82,"digital":84,"human":75,"infra":84,"sustain":68,"internet_pct":97,"sectors":["C","J","K","D"]},
    {"iso3":"LAO","iso2":"LA","name":"Lao PDR",              "region":"EAP","income":"LMIC","pop_m":7.4,  "gdp_b":15,  "fdi_b":1.5,"gfr":40.0,"rank":132,"tier":"EMERGING","macro":44,"policy":36,"digital":36,"human":34,"infra":42,"sustain":38,"internet_pct":30,"sectors":["B","D","H"]},
    {"iso3":"MAC","iso2":"MO","name":"Macao SAR",            "region":"EAP","income":"HIC","pop_m":0.7,  "gdp_b":34,  "fdi_b":2.1,"gfr":68.0,"rank":30,"tier":"HIGH",   "macro":72,"policy":65,"digital":78,"human":55,"infra":80,"sustain":48,"internet_pct":90,"sectors":["L","K","J"]},
    {"iso3":"MHL","iso2":"MH","name":"Marshall Islands",     "region":"EAP","income":"UMIC","pop_m":0.04, "gdp_b":0.3, "fdi_b":0.0,"gfr":24.0,"rank":205,"tier":"DEVELOPING","macro":26,"policy":22,"digital":20,"human":26,"infra":22,"sustain":28,"internet_pct":26,"sectors":["Q"]},
    {"iso3":"MMR","iso2":"MM","name":"Myanmar",              "region":"EAP","income":"LMIC","pop_m":55,  "gdp_b":65,  "fdi_b":1.5,"gfr":30.0,"rank":168,"tier":"DEVELOPING","macro":32,"policy":22,"digital":28,"human":28,"infra":32,"sustain":34,"internet_pct":38,"sectors":["C","B","D"]},
    {"iso3":"MNG","iso2":"MN","name":"Mongolia",             "region":"EAP","income":"LMIC","pop_m":3.4,  "gdp_b":18,  "fdi_b":2.4,"gfr":42.0,"rank":127,"tier":"EMERGING","macro":46,"policy":44,"digital":45,"human":52,"infra":35,"sustain":38,"internet_pct":78,"sectors":["B","D"]},
    {"iso3":"MYS","iso2":"MY","name":"Malaysia",             "region":"EAP","income":"UMIC","pop_m":33,  "gdp_b":430, "fdi_b":14.2,"gfr":66.4,"rank":35,"tier":"HIGH",   "macro":68,"policy":65,"digital":72,"human":58,"infra":68,"sustain":58,"internet_pct":97,"sectors":["C","J","K","D"]},
    {"iso3":"NRU","iso2":"NR","name":"Nauru",                "region":"EAP","income":"HIC","pop_m":0.01, "gdp_b":0.1, "fdi_b":0.0,"gfr":22.0,"rank":209,"tier":"DEVELOPING","macro":24,"policy":18,"digital":18,"human":22,"infra":20,"sustain":26,"internet_pct":58,"sectors":["Q"]},
    {"iso3":"NZL","iso2":"NZ","name":"New Zealand",          "region":"EAP","income":"HIC","pop_m":5.1,  "gdp_b":245, "fdi_b":11.4,"gfr":82.0,"rank":9, "tier":"FRONTIER","macro":84,"policy":88,"digital":82,"human":76,"infra":80,"sustain":82,"internet_pct":96,"sectors":["D","L","K","J"]},
    {"iso3":"PHL","iso2":"PH","name":"Philippines",          "region":"EAP","income":"LMIC","pop_m":115,  "gdp_b":435, "fdi_b":9.5,"gfr":52.0,"rank":88,"tier":"MEDIUM", "macro":58,"policy":50,"digital":55,"human":55,"infra":48,"sustain":44,"internet_pct":73,"sectors":["C","J","K","H"]},
    {"iso3":"PLW","iso2":"PW","name":"Palau",                "region":"EAP","income":"HIC","pop_m":0.02, "gdp_b":0.3, "fdi_b":0.0,"gfr":35.0,"rank":158,"tier":"DEVELOPING","macro":38,"policy":32,"digital":38,"human":34,"infra":32,"sustain":38,"internet_pct":58,"sectors":["Q","L"]},
    {"iso3":"PNG","iso2":"PG","name":"Papua New Guinea",     "region":"EAP","income":"LMIC","pop_m":10,  "gdp_b":30,  "fdi_b":1.8,"gfr":34.0,"rank":162,"tier":"DEVELOPING","macro":36,"policy":32,"digital":26,"human":30,"infra":34,"sustain":38,"internet_pct":24,"sectors":["B","D","C"]},
    {"iso3":"PRK","iso2":"KP","name":"Korea, Dem. Rep.",     "region":"EAP","income":"LIC","pop_m":26,  "gdp_b":17,  "fdi_b":0.1,"gfr":8.0,"rank":215,"tier":"DEVELOPING","macro":10,"policy":4,"digital":8,"human":14,"infra":12,"sustain":8,"internet_pct":0,"sectors":["B","C"]},
    {"iso3":"SGP","iso2":"SG","name":"Singapore",            "region":"EAP","income":"HIC","pop_m":5.9,  "gdp_b":501, "fdi_b":141.2,"gfr":88.5,"rank":1, "tier":"FRONTIER","macro":87,"policy":91,"digital":87,"human":63,"infra":94,"sustain":62,"internet_pct":97,"sectors":["J","K","H","L"]},
    {"iso3":"SLB","iso2":"SB","name":"Solomon Islands",      "region":"EAP","income":"LMIC","pop_m":0.7,  "gdp_b":1.7, "fdi_b":0.1,"gfr":26.0,"rank":198,"tier":"DEVELOPING","macro":28,"policy":24,"digital":22,"human":28,"infra":24,"sustain":34,"internet_pct":18,"sectors":["B","Q"]},
    {"iso3":"THA","iso2":"TH","name":"Thailand",             "region":"EAP","income":"UMIC","pop_m":71,  "gdp_b":545, "fdi_b":9.8,"gfr":63.1,"rank":42,"tier":"MEDIUM", "macro":66,"policy":60,"digital":68,"human":54,"infra":68,"sustain":58,"internet_pct":84,"sectors":["C","H","J","D"]},
    {"iso3":"TLS","iso2":"TL","name":"Timor-Leste",          "region":"EAP","income":"LMIC","pop_m":1.3,  "gdp_b":2.2, "fdi_b":0.1,"gfr":28.0,"rank":185,"tier":"DEVELOPING","macro":30,"policy":26,"digital":22,"human":26,"infra":28,"sustain":34,"internet_pct":30,"sectors":["B","Q"]},
    {"iso3":"TON","iso2":"TO","name":"Tonga",                "region":"EAP","income":"UMIC","pop_m":0.1,  "gdp_b":0.5, "fdi_b":0.0,"gfr":34.0,"rank":163,"tier":"DEVELOPING","macro":36,"policy":32,"digital":32,"human":38,"infra":28,"sustain":38,"internet_pct":52,"sectors":["Q","L"]},
    {"iso3":"TUV","iso2":"TV","name":"Tuvalu",               "region":"EAP","income":"UMIC","pop_m":0.01, "gdp_b":0.1, "fdi_b":0.0,"gfr":21.0,"rank":211,"tier":"DEVELOPING","macro":22,"policy":18,"digital":16,"human":22,"infra":18,"sustain":28,"internet_pct":48,"sectors":["Q"]},
    {"iso3":"VNM","iso2":"VN","name":"Vietnam",              "region":"EAP","income":"LMIC","pop_m":97,  "gdp_b":430, "fdi_b":18.1,"gfr":58.2,"rank":63,"tier":"MEDIUM", "macro":62,"policy":58,"digital":55,"human":52,"infra":58,"sustain":48,"internet_pct":79,"sectors":["C","J","D","H"]},
    {"iso3":"VUT","iso2":"VU","name":"Vanuatu",              "region":"EAP","income":"LMIC","pop_m":0.3,  "gdp_b":1.0, "fdi_b":0.1,"gfr":28.0,"rank":186,"tier":"DEVELOPING","macro":30,"policy":26,"digital":24,"human":28,"infra":26,"sustain":38,"internet_pct":28,"sectors":["Q","L"]},
    {"iso3":"WSM","iso2":"WS","name":"Samoa",                "region":"EAP","income":"UMIC","pop_m":0.2,  "gdp_b":0.9, "fdi_b":0.0,"gfr":34.0,"rank":164,"tier":"DEVELOPING","macro":36,"policy":30,"digital":32,"human":36,"infra":28,"sustain":38,"internet_pct":45,"sectors":["Q","L"]},

    # ── EUROPE & CENTRAL ASIA ─────────────────────────────────────────────
    {"iso3":"ALB","iso2":"AL","name":"Albania",              "region":"ECA","income":"UMIC","pop_m":2.8,  "gdp_b":20,  "fdi_b":1.2,"gfr":48.0,"rank":102,"tier":"MEDIUM", "macro":50,"policy":46,"digital":52,"human":44,"infra":46,"sustain":48,"internet_pct":82,"sectors":["L","H","D"]},
    {"iso3":"ARM","iso2":"AM","name":"Armenia",              "region":"ECA","income":"UMIC","pop_m":3.0,  "gdp_b":24,  "fdi_b":0.8,"gfr":45.0,"rank":115,"tier":"MEDIUM", "macro":48,"policy":44,"digital":52,"human":50,"infra":38,"sustain":42,"internet_pct":80,"sectors":["J","K","D"]},
    {"iso3":"AUT","iso2":"AT","name":"Austria",              "region":"ECA","income":"HIC","pop_m":9.1,  "gdp_b":470, "fdi_b":8.2,"gfr":79.0,"rank":13,"tier":"HIGH",   "macro":80,"policy":84,"digital":78,"human":72,"infra":82,"sustain":78,"internet_pct":92,"sectors":["K","C","J","L"]},
    {"iso3":"AZE","iso2":"AZ","name":"Azerbaijan",           "region":"ECA","income":"UMIC","pop_m":10,  "gdp_b":78,  "fdi_b":3.1,"gfr":48.0,"rank":101,"tier":"MEDIUM", "macro":55,"policy":42,"digital":48,"human":44,"infra":50,"sustain":42,"internet_pct":82,"sectors":["B","D","H"]},
    {"iso3":"BEL","iso2":"BE","name":"Belgium",              "region":"ECA","income":"HIC","pop_m":11.6, "gdp_b":579, "fdi_b":31.2,"gfr":76.2,"rank":17,"tier":"HIGH",   "macro":78,"policy":80,"digital":76,"human":68,"infra":78,"sustain":74,"internet_pct":94,"sectors":["K","C","J","H"]},
    {"iso3":"BGR","iso2":"BG","name":"Bulgaria",             "region":"ECA","income":"UMIC","pop_m":6.4,  "gdp_b":97,  "fdi_b":2.8,"gfr":52.0,"rank":87,"tier":"MEDIUM", "macro":54,"policy":50,"digital":58,"human":46,"infra":50,"sustain":52,"internet_pct":83,"sectors":["C","J","K"]},
    {"iso3":"BIH","iso2":"BA","name":"Bosnia and Herzegovina","region":"ECA","income":"UMIC","pop_m":3.3, "gdp_b":26,  "fdi_b":0.5,"gfr":40.0,"rank":133,"tier":"EMERGING","macro":42,"policy":36,"digital":44,"human":38,"infra":38,"sustain":40,"internet_pct":78,"sectors":["C","L"]},
    {"iso3":"BLR","iso2":"BY","name":"Belarus",              "region":"ECA","income":"UMIC","pop_m":9.4,  "gdp_b":73,  "fdi_b":1.2,"gfr":40.0,"rank":134,"tier":"EMERGING","macro":44,"policy":32,"digital":52,"human":48,"infra":42,"sustain":38,"internet_pct":86,"sectors":["C","J","D"]},
    {"iso3":"CHE","iso2":"CH","name":"Switzerland",          "region":"ECA","income":"HIC","pop_m":8.7,  "gdp_b":884, "fdi_b":26.4,"gfr":87.5,"rank":2, "tier":"FRONTIER","macro":88,"policy":90,"digital":85,"human":78,"infra":91,"sustain":74,"internet_pct":97,"sectors":["K","J","C","L"]},
    {"iso3":"CYP","iso2":"CY","name":"Cyprus",               "region":"ECA","income":"HIC","pop_m":1.2,  "gdp_b":30,  "fdi_b":18.4,"gfr":62.0,"rank":46,"tier":"MEDIUM", "macro":64,"policy":62,"digital":70,"human":58,"infra":62,"sustain":55,"internet_pct":90,"sectors":["K","L","J"]},
    {"iso3":"CZE","iso2":"CZ","name":"Czech Republic",       "region":"ECA","income":"HIC","pop_m":10.8, "gdp_b":330, "fdi_b":11.8,"gfr":66.0,"rank":36,"tier":"HIGH",   "macro":68,"policy":68,"digital":72,"human":62,"infra":68,"sustain":62,"internet_pct":90,"sectors":["C","J","K"]},
    {"iso3":"DEU","iso2":"DE","name":"Germany",              "region":"ECA","income":"HIC","pop_m":83,   "gdp_b":4430,"fdi_b":35.4,"gfr":78.1,"rank":4, "TIER":"HIGH",   "macro":81,"policy":86,"digital":78,"human":70,"infra":84,"sustain":77,"internet_pct":94,"sectors":["C","J","D","K"]},
    {"iso3":"DNK","iso2":"DK","name":"Denmark",              "region":"ECA","income":"HIC","pop_m":5.9,  "gdp_b":395, "fdi_b":14.8,"gfr":84.2,"rank":7, "tier":"FRONTIER","macro":86,"policy":90,"digital":86,"human":76,"infra":82,"sustain":90,"internet_pct":98,"sectors":["D","J","K","C"]},
    {"iso3":"ESP","iso2":"ES","name":"Spain",                "region":"ECA","income":"HIC","pop_m":47,   "gdp_b":1580,"fdi_b":27.4,"gfr":70.0,"rank":24,"tier":"HIGH",   "macro":72,"policy":72,"digital":72,"human":62,"infra":72,"sustain":70,"internet_pct":95,"sectors":["L","K","D","J"]},
    {"iso3":"EST","iso2":"EE","name":"Estonia",              "region":"ECA","income":"HIC","pop_m":1.3,  "gdp_b":41,  "fdi_b":2.4,"gfr":72.0,"rank":22,"tier":"HIGH",   "macro":72,"policy":76,"digital":82,"human":62,"infra":68,"sustain":70,"internet_pct":92,"sectors":["J","K","C"]},
    {"iso3":"FIN","iso2":"FI","name":"Finland",              "region":"ECA","income":"HIC","pop_m":5.5,  "gdp_b":305, "fdi_b":8.4,"gfr":82.8,"rank":8, "tier":"FRONTIER","macro":84,"policy":88,"digital":86,"human":76,"infra":80,"sustain":88,"internet_pct":94,"sectors":["C","J","D","K"]},
    {"iso3":"FRA","iso2":"FR","name":"France",               "region":"ECA","income":"HIC","pop_m":68,   "gdp_b":2924,"fdi_b":28.1,"gfr":76.2,"rank":16,"tier":"HIGH",   "macro":78,"policy":76,"digital":76,"human":66,"infra":80,"sustain":76,"internet_pct":92,"sectors":["C","K","D","J"]},
    {"iso3":"GBR","iso2":"GB","name":"United Kingdom",       "region":"ECA","income":"HIC","pop_m":67,   "gdp_b":3079,"fdi_b":52.0,"gfr":78.5,"rank":5, "tier":"HIGH",   "macro":80,"policy":84,"digital":82,"human":71,"infra":80,"sustain":72,"internet_pct":97,"sectors":["K","J","L","C"]},
    {"iso3":"GEO","iso2":"GE","name":"Georgia",              "region":"ECA","income":"UMIC","pop_m":3.7,  "gdp_b":28,  "fdi_b":1.8,"gfr":48.0,"rank":103,"tier":"MEDIUM", "macro":50,"policy":52,"digital":58,"human":48,"infra":42,"sustain":42,"internet_pct":80,"sectors":["L","J","K"]},
    {"iso3":"GRC","iso2":"GR","name":"Greece",               "region":"ECA","income":"HIC","pop_m":10.4, "gdp_b":240, "fdi_b":5.4,"gfr":62.0,"rank":47,"tier":"MEDIUM", "macro":62,"policy":60,"digital":62,"human":55,"infra":62,"sustain":62,"internet_pct":88,"sectors":["L","K","D"]},
    {"iso3":"HRV","iso2":"HR","name":"Croatia",              "region":"ECA","income":"HIC","pop_m":3.8,  "gdp_b":80,  "fdi_b":2.4,"gfr":60.0,"rank":51,"tier":"MEDIUM", "macro":62,"policy":60,"digital":64,"human":54,"infra":60,"sustain":60,"internet_pct":82,"sectors":["L","K","C"]},
    {"iso3":"HUN","iso2":"HU","name":"Hungary",              "region":"ECA","income":"HIC","pop_m":9.7,  "gdp_b":210, "fdi_b":8.2,"gfr":58.0,"rank":64,"tier":"MEDIUM", "macro":60,"policy":52,"digital":66,"human":56,"infra":60,"sustain":55,"internet_pct":88,"sectors":["C","J","K"]},
    {"iso3":"IRL","iso2":"IE","name":"Ireland",              "region":"ECA","income":"HIC","pop_m":5.1,  "gdp_b":529, "fdi_b":94.5,"gfr":76.5,"rank":15,"tier":"HIGH",   "macro":82,"policy":80,"digital":80,"human":72,"infra":78,"sustain":68,"internet_pct":92,"sectors":["J","K","C","L"]},
    {"iso3":"ISL","iso2":"IS","name":"Iceland",              "region":"ECA","income":"HIC","pop_m":0.4,  "gdp_b":28,  "fdi_b":1.2,"gfr":80.0,"rank":11,"tier":"FRONTIER","macro":82,"policy":86,"digital":84,"human":74,"infra":78,"sustain":88,"internet_pct":99,"sectors":["D","L","K"]},
    {"iso3":"ITA","iso2":"IT","name":"Italy",                "region":"ECA","income":"HIC","pop_m":59,   "gdp_b":2169,"fdi_b":22.1,"gfr":68.0,"rank":29,"tier":"HIGH",   "macro":70,"policy":66,"digital":66,"human":60,"infra":72,"sustain":70,"internet_pct":90,"sectors":["C","K","L","D"]},
    {"iso3":"KAZ","iso2":"KZ","name":"Kazakhstan",           "region":"ECA","income":"UMIC","pop_m":19,  "gdp_b":259, "fdi_b":8.1,"gfr":52.0,"rank":90,"tier":"MEDIUM", "macro":58,"policy":48,"digital":55,"human":50,"infra":52,"sustain":42,"internet_pct":82,"sectors":["B","D","C"]},
    {"iso3":"KGZ","iso2":"KG","name":"Kyrgyz Republic",      "region":"ECA","income":"LMIC","pop_m":7,   "gdp_b":12,  "fdi_b":0.5,"gfr":36.0,"rank":155,"tier":"DEVELOPING","macro":38,"policy":34,"digital":40,"human":40,"infra":30,"sustain":35,"internet_pct":62,"sectors":["B","D"]},
    {"iso3":"LIE","iso2":"LI","name":"Liechtenstein",        "region":"ECA","income":"HIC","pop_m":0.04, "gdp_b":7.3, "fdi_b":3.2,"gfr":78.0,"rank":13,"tier":"HIGH",   "macro":80,"policy":82,"digital":78,"human":72,"infra":78,"sustain":72,"internet_pct":98,"sectors":["K","J","C"]},
    {"iso3":"LTU","iso2":"LT","name":"Lithuania",            "region":"ECA","income":"HIC","pop_m":2.8,  "gdp_b":75,  "fdi_b":2.4,"gfr":64.0,"rank":39,"tier":"HIGH",   "macro":66,"policy":68,"digital":72,"human":58,"infra":62,"sustain":62,"internet_pct":86,"sectors":["J","C","K"]},
    {"iso3":"LUX","iso2":"LU","name":"Luxembourg",           "region":"ECA","income":"HIC","pop_m":0.7,  "gdp_b":82,  "fdi_b":48.0,"gfr":80.0,"rank":10,"tier":"FRONTIER","macro":82,"policy":84,"digital":82,"human":70,"infra":82,"sustain":74,"internet_pct":99,"sectors":["K","J","L"]},
    {"iso3":"LVA","iso2":"LV","name":"Latvia",               "region":"ECA","income":"HIC","pop_m":1.8,  "gdp_b":44,  "fdi_b":1.5,"gfr":62.0,"rank":48,"tier":"MEDIUM", "macro":62,"policy":66,"digital":72,"human":58,"infra":58,"sustain":60,"internet_pct":86,"sectors":["C","J","K"]},
    {"iso3":"MDA","iso2":"MD","name":"Moldova",              "region":"ECA","income":"LMIC","pop_m":2.6,  "gdp_b":15,  "fdi_b":0.5,"gfr":38.0,"rank":148,"tier":"EMERGING","macro":40,"policy":36,"digital":42,"human":40,"infra":32,"sustain":38,"internet_pct":75,"sectors":["C","L"]},
    {"iso3":"MKD","iso2":"MK","name":"North Macedonia",      "region":"ECA","income":"UMIC","pop_m":2.1,  "gdp_b":15,  "fdi_b":0.4,"gfr":42.0,"rank":129,"tier":"EMERGING","macro":44,"policy":40,"digital":48,"human":40,"infra":40,"sustain":40,"internet_pct":82,"sectors":["C","J"]},
    {"iso3":"MLT","iso2":"MT","name":"Malta",                "region":"ECA","income":"HIC","pop_m":0.5,  "gdp_b":19,  "fdi_b":8.2,"gfr":66.0,"rank":33,"tier":"HIGH",   "macro":68,"policy":68,"digital":74,"human":60,"infra":66,"sustain":58,"internet_pct":88,"sectors":["K","J","L"]},
    {"iso3":"MNE","iso2":"ME","name":"Montenegro",           "region":"ECA","income":"UMIC","pop_m":0.6,  "gdp_b":7.4, "fdi_b":0.8,"gfr":44.0,"rank":118,"tier":"MEDIUM", "macro":46,"policy":42,"digital":50,"human":44,"infra":42,"sustain":42,"internet_pct":82,"sectors":["L","K"]},
    {"iso3":"NLD","iso2":"NL","name":"Netherlands",          "region":"ECA","income":"HIC","pop_m":17.6, "gdp_b":1081,"fdi_b":92.4,"gfr":80.5,"rank":9, "tier":"FRONTIER","macro":82,"policy":86,"digital":84,"human":72,"infra":84,"sustain":78,"internet_pct":95,"sectors":["K","J","H","C"]},
    {"iso3":"NOR","iso2":"NO","name":"Norway",               "region":"ECA","income":"HIC","pop_m":5.4,  "gdp_b":485, "fdi_b":12.3,"gfr":83.2,"rank":8, "tier":"FRONTIER","macro":85,"policy":88,"digital":84,"human":75,"infra":82,"sustain":91,"internet_pct":99,"sectors":["D","K","J","C"]},
    {"iso3":"POL","iso2":"PL","name":"Poland",               "region":"ECA","income":"HIC","pop_m":38,   "gdp_b":750, "fdi_b":20.8,"gfr":62.0,"rank":44,"tier":"MEDIUM", "macro":64,"policy":58,"digital":66,"human":58,"infra":62,"sustain":58,"internet_pct":90,"sectors":["C","J","K"]},
    {"iso3":"PRT","iso2":"PT","name":"Portugal",             "region":"ECA","income":"HIC","pop_m":10.2, "gdp_b":278, "fdi_b":8.4,"gfr":66.0,"rank":34,"tier":"HIGH",   "macro":68,"policy":70,"digital":68,"human":58,"infra":68,"sustain":65,"internet_pct":82,"sectors":["L","K","J","D"]},
    {"iso3":"ROU","iso2":"RO","name":"Romania",              "region":"ECA","income":"HIC","pop_m":19,   "gdp_b":350, "fdi_b":9.1,"gfr":54.0,"rank":82,"tier":"MEDIUM", "macro":56,"policy":50,"digital":60,"human":50,"infra":52,"sustain":52,"internet_pct":88,"sectors":["C","J","K"]},
    {"iso3":"RUS","iso2":"RU","name":"Russian Federation",   "region":"ECA","income":"UMIC","pop_m":143,  "gdp_b":1862,"fdi_b":5.2,"gfr":38.0,"rank":147,"tier":"EMERGING","macro":44,"policy":28,"digital":55,"human":52,"infra":50,"sustain":28,"internet_pct":88,"sectors":["D","B","C"]},
    {"iso3":"SRB","iso2":"RS","name":"Serbia",               "region":"ECA","income":"UMIC","pop_m":6.8,  "gdp_b":70,  "fdi_b":4.0,"gfr":48.0,"rank":104,"tier":"MEDIUM", "macro":50,"policy":48,"digital":55,"human":46,"infra":46,"sustain":44,"internet_pct":82,"sectors":["C","J","L"]},
    {"iso3":"SVK","iso2":"SK","name":"Slovak Republic",      "region":"ECA","income":"HIC","pop_m":5.5,  "gdp_b":136, "fdi_b":2.1,"gfr":62.0,"rank":49,"tier":"MEDIUM", "macro":64,"policy":62,"digital":66,"human":56,"infra":62,"sustain":58,"internet_pct":90,"sectors":["C","J","K"]},
    {"iso3":"SVN","iso2":"SI","name":"Slovenia",             "region":"ECA","income":"HIC","pop_m":2.1,  "gdp_b":70,  "fdi_b":1.8,"gfr":68.0,"rank":28,"tier":"HIGH",   "macro":70,"policy":70,"digital":74,"human":62,"infra":68,"sustain":68,"internet_pct":91,"sectors":["C","J","K"]},
    {"iso3":"SWE","iso2":"SE","name":"Sweden",               "region":"ECA","income":"HIC","pop_m":10.5, "gdp_b":597, "fdi_b":14.8,"gfr":84.0,"rank":5, "tier":"FRONTIER","macro":86,"policy":88,"digital":86,"human":76,"infra":82,"sustain":90,"internet_pct":97,"sectors":["C","J","K","D"]},
    {"iso3":"TJK","iso2":"TJ","name":"Tajikistan",           "region":"ECA","income":"LIC","pop_m":10,  "gdp_b":10,  "fdi_b":0.3,"gfr":28.0,"rank":188,"tier":"DEVELOPING","macro":30,"policy":24,"digital":28,"human":28,"infra":24,"sustain":28,"internet_pct":30,"sectors":["B","D"]},
    {"iso3":"TKM","iso2":"TM","name":"Turkmenistan",         "region":"ECA","income":"UMIC","pop_m":6.1,  "gdp_b":59,  "fdi_b":1.4,"gfr":26.0,"rank":196,"tier":"DEVELOPING","macro":30,"policy":18,"digital":22,"human":24,"infra":30,"sustain":22,"internet_pct":18,"sectors":["D","B"]},
    {"iso3":"TUR","iso2":"TR","name":"Turkey",               "region":"ECA","income":"UMIC","pop_m":85,   "gdp_b":1108,"fdi_b":12.4,"gfr":52.0,"rank":89,"tier":"MEDIUM", "macro":56,"policy":44,"digital":60,"human":50,"infra":60,"sustain":46,"internet_pct":88,"sectors":["C","L","K","D"]},
    {"iso3":"UKR","iso2":"UA","name":"Ukraine",              "region":"ECA","income":"LMIC","pop_m":42,   "gdp_b":178, "fdi_b":1.8,"gfr":36.0,"rank":154,"tier":"DEVELOPING","macro":35,"policy":34,"digital":55,"human":50,"infra":32,"sustain":28,"internet_pct":81,"sectors":["C","D","B"]},
    {"iso3":"UZB","iso2":"UZ","name":"Uzbekistan",           "region":"ECA","income":"LMIC","pop_m":35,   "gdp_b":100, "fdi_b":2.8,"gfr":40.0,"rank":136,"tier":"EMERGING","macro":44,"policy":38,"digital":42,"human":40,"infra":38,"sustain":36,"internet_pct":72,"sectors":["D","C","B"]},
    {"iso3":"XKX","iso2":"XK","name":"Kosovo",               "region":"ECA","income":"UMIC","pop_m":1.8,  "gdp_b":10,  "fdi_b":0.4,"gfr":36.0,"rank":156,"tier":"DEVELOPING","macro":38,"policy":34,"digital":42,"human":36,"infra":32,"sustain":34,"internet_pct":76,"sectors":["C","L"]},

    # ── LATIN AMERICA & CARIBBEAN ─────────────────────────────────────────
    {"iso3":"ARG","iso2":"AR","name":"Argentina",            "region":"LAC","income":"UMIC","pop_m":46,   "gdp_b":620, "fdi_b":7.3,"gfr":48.0,"rank":105,"tier":"MEDIUM", "macro":42,"policy":42,"digital":55,"human":56,"infra":48,"sustain":44,"internet_pct":88,"sectors":["B","D","C","K"]},
    {"iso3":"ATG","iso2":"AG","name":"Antigua and Barbuda",  "region":"LAC","income":"HIC","pop_m":0.1,  "gdp_b":2.0, "fdi_b":0.3,"gfr":44.0,"rank":117,"tier":"MEDIUM", "macro":46,"policy":44,"digital":50,"human":42,"infra":42,"sustain":40,"internet_pct":76,"sectors":["L","K"]},
    {"iso3":"BHS","iso2":"BS","name":"Bahamas",              "region":"LAC","income":"HIC","pop_m":0.4,  "gdp_b":13,  "fdi_b":0.8,"gfr":50.0,"rank":96,"tier":"MEDIUM", "macro":52,"policy":52,"digital":58,"human":46,"infra":50,"sustain":44,"internet_pct":80,"sectors":["L","K","J"]},
    {"iso3":"BLZ","iso2":"BZ","name":"Belize",               "region":"LAC","income":"UMIC","pop_m":0.4,  "gdp_b":2.8, "fdi_b":0.2,"gfr":38.0,"rank":146,"tier":"EMERGING","macro":40,"policy":36,"digital":38,"human":36,"infra":36,"sustain":40,"internet_pct":55,"sectors":["Q","L","B"]},
    {"iso3":"BOL","iso2":"BO","name":"Bolivia",              "region":"LAC","income":"LMIC","pop_m":12,   "gdp_b":44,  "fdi_b":0.8,"gfr":38.0,"rank":150,"tier":"EMERGING","macro":42,"policy":34,"digital":38,"human":40,"infra":34,"sustain":36,"internet_pct":55,"sectors":["B","D","C"]},
    {"iso3":"BRA","iso2":"BR","name":"Brazil",               "region":"LAC","income":"UMIC","pop_m":214,  "gdp_b":2130,"fdi_b":65.1,"gfr":54.2,"rank":80,"tier":"MEDIUM", "macro":58,"policy":52,"digital":62,"human":56,"infra":52,"sustain":44,"internet_pct":84,"sectors":["D","K","C","B"]},
    {"iso3":"BRB","iso2":"BB","name":"Barbados",             "region":"LAC","income":"HIC","pop_m":0.3,  "gdp_b":5.7, "fdi_b":0.3,"gfr":52.0,"rank":86,"tier":"MEDIUM", "macro":54,"policy":54,"digital":60,"human":48,"infra":50,"sustain":48,"internet_pct":82,"sectors":["K","L","J"]},
    {"iso3":"CHL","iso2":"CL","name":"Chile",                "region":"LAC","income":"HIC","pop_m":19,   "gdp_b":335, "fdi_b":16.8,"gfr":60.0,"rank":52,"tier":"MEDIUM", "macro":62,"policy":64,"digital":64,"human":54,"infra":60,"sustain":52,"internet_pct":90,"sectors":["B","D","K","L"]},
    {"iso3":"COL","iso2":"CO","name":"Colombia",             "region":"LAC","income":"UMIC","pop_m":52,   "gdp_b":344, "fdi_b":17.2,"gfr":52.0,"rank":91,"tier":"MEDIUM", "macro":54,"policy":50,"digital":55,"human":50,"infra":50,"sustain":46,"internet_pct":72,"sectors":["D","K","C","B"]},
    {"iso3":"CRI","iso2":"CR","name":"Costa Rica",           "region":"LAC","income":"UMIC","pop_m":5.2,  "gdp_b":67,  "fdi_b":3.8,"gfr":56.0,"rank":70,"tier":"MEDIUM", "macro":58,"policy":58,"digital":60,"human":54,"infra":52,"sustain":54,"internet_pct":82,"sectors":["J","C","K","L"]},
    {"iso3":"CUB","iso2":"CU","name":"Cuba",                 "region":"LAC","income":"UMIC","pop_m":11,   "gdp_b":107, "fdi_b":0.1,"gfr":22.0,"rank":210,"tier":"DEVELOPING","macro":25,"policy":12,"digital":25,"human":30,"infra":24,"sustain":22,"internet_pct":68,"sectors":["Q","D"]},
    {"iso3":"DOM","iso2":"DO","name":"Dominican Republic",   "region":"LAC","income":"UMIC","pop_m":11,   "gdp_b":120, "fdi_b":4.0,"gfr":48.0,"rank":106,"tier":"MEDIUM", "macro":50,"policy":46,"digital":55,"human":44,"infra":46,"sustain":42,"internet_pct":72,"sectors":["L","C","K"]},
    {"iso3":"ECU","iso2":"EC","name":"Ecuador",              "region":"LAC","income":"UMIC","pop_m":18,   "gdp_b":116, "fdi_b":1.4,"gfr":44.0,"rank":120,"tier":"MEDIUM", "macro":46,"policy":40,"digital":48,"human":44,"infra":42,"sustain":40,"internet_pct":65,"sectors":["B","D","C"]},
    {"iso3":"GRD","iso2":"GD","name":"Grenada",              "region":"LAC","income":"UMIC","pop_m":0.1,  "gdp_b":1.3, "fdi_b":0.1,"gfr":42.0,"rank":125,"tier":"EMERGING","macro":44,"policy":42,"digital":46,"human":40,"infra":38,"sustain":42,"internet_pct":72,"sectors":["L","Q"]},
    {"iso3":"GTM","iso2":"GT","name":"Guatemala",            "region":"LAC","income":"UMIC","pop_m":18,   "gdp_b":95,  "fdi_b":1.5,"gfr":40.0,"rank":137,"tier":"EMERGING","macro":42,"policy":36,"digital":38,"human":36,"infra":38,"sustain":36,"internet_pct":56,"sectors":["C","B","L"]},
    {"iso3":"GUY","iso2":"GY","name":"Guyana",               "region":"LAC","income":"UMIC","pop_m":0.8,  "gdp_b":16,  "fdi_b":3.8,"gfr":44.0,"rank":119,"tier":"MEDIUM", "macro":50,"policy":42,"digital":42,"human":40,"infra":40,"sustain":42,"internet_pct":68,"sectors":["B","D","C"]},
    {"iso3":"HND","iso2":"HN","name":"Honduras",             "region":"LAC","income":"LMIC","pop_m":10,   "gdp_b":32,  "fdi_b":1.0,"gfr":36.0,"rank":157,"tier":"DEVELOPING","macro":38,"policy":32,"digital":35,"human":32,"infra":34,"sustain":36,"internet_pct":50,"sectors":["C","B","L"]},
    {"iso3":"HTI","iso2":"HT","name":"Haiti",                "region":"LAC","income":"LIC","pop_m":12,   "gdp_b":19,  "fdi_b":0.2,"gfr":18.0,"rank":213,"tier":"DEVELOPING","macro":18,"policy":14,"digital":16,"human":18,"infra":16,"sustain":22,"internet_pct":32,"sectors":["C","L"]},
    {"iso3":"JAM","iso2":"JM","name":"Jamaica",              "region":"LAC","income":"UMIC","pop_m":3.0,  "gdp_b":17,  "fdi_b":0.5,"gfr":44.0,"rank":121,"tier":"MEDIUM", "macro":46,"policy":44,"digital":50,"human":42,"infra":40,"sustain":40,"internet_pct":74,"sectors":["L","C","K"]},
    {"iso3":"KNA","iso2":"KN","name":"St. Kitts and Nevis",  "region":"LAC","income":"HIC","pop_m":0.05, "gdp_b":1.1, "fdi_b":0.2,"gfr":44.0,"rank":122,"tier":"MEDIUM", "macro":46,"policy":44,"digital":48,"human":40,"infra":42,"sustain":42,"internet_pct":75,"sectors":["L","K"]},
    {"iso3":"LCA","iso2":"LC","name":"St. Lucia",            "region":"LAC","income":"UMIC","pop_m":0.2,  "gdp_b":2.2, "fdi_b":0.2,"gfr":44.0,"rank":123,"tier":"MEDIUM", "macro":46,"policy":44,"digital":48,"human":40,"infra":42,"sustain":42,"internet_pct":74,"sectors":["L","K"]},
    {"iso3":"MEX","iso2":"MX","name":"Mexico",               "region":"LAC","income":"UMIC","pop_m":127,  "gdp_b":1328,"fdi_b":36.1,"gfr":54.0,"rank":81,"tier":"MEDIUM", "macro":56,"policy":50,"digital":60,"human":48,"infra":54,"sustain":52,"internet_pct":76,"sectors":["C","D","K","B"]},
    {"iso3":"NIC","iso2":"NI","name":"Nicaragua",            "region":"LAC","income":"LMIC","pop_m":6.7,  "gdp_b":17,  "fdi_b":0.6,"gfr":34.0,"rank":165,"tier":"DEVELOPING","macro":36,"policy":28,"digital":32,"human":32,"infra":32,"sustain":36,"internet_pct":46,"sectors":["C","B","D"]},
    {"iso3":"PAN","iso2":"PA","name":"Panama",               "region":"LAC","income":"HIC","pop_m":4.4,  "gdp_b":74,  "fdi_b":3.2,"gfr":56.0,"rank":71,"tier":"MEDIUM", "macro":58,"policy":56,"digital":62,"human":48,"infra":58,"sustain":52,"internet_pct":74,"sectors":["K","H","L","J"]},
    {"iso3":"PER","iso2":"PE","name":"Peru",                 "region":"LAC","income":"UMIC","pop_m":33,   "gdp_b":260, "fdi_b":8.4,"gfr":48.0,"rank":107,"tier":"MEDIUM", "macro":52,"policy":46,"digital":50,"human":46,"infra":46,"sustain":44,"internet_pct":68,"sectors":["B","D","K","C"]},
    {"iso3":"PRY","iso2":"PY","name":"Paraguay",             "region":"LAC","income":"UMIC","pop_m":7.4,  "gdp_b":42,  "fdi_b":0.5,"gfr":40.0,"rank":138,"tier":"EMERGING","macro":42,"policy":36,"digital":40,"human":36,"infra":38,"sustain":42,"internet_pct":68,"sectors":["D","C","B"]},
    {"iso3":"SLV","iso2":"SV","name":"El Salvador",          "region":"LAC","income":"UMIC","pop_m":6.5,  "gdp_b":35,  "fdi_b":0.8,"gfr":40.0,"rank":139,"tier":"EMERGING","macro":42,"policy":36,"digital":42,"human":36,"infra":38,"sustain":38,"internet_pct":62,"sectors":["C","L","K"]},
    {"iso3":"SUR","iso2":"SR","name":"Suriname",             "region":"LAC","income":"UMIC","pop_m":0.6,  "gdp_b":4.0, "fdi_b":0.3,"gfr":38.0,"rank":149,"tier":"EMERGING","macro":40,"policy":32,"digital":38,"human":36,"infra":36,"sustain":38,"internet_pct":68,"sectors":["B","D"]},
    {"iso3":"TTO","iso2":"TT","name":"Trinidad and Tobago",  "region":"LAC","income":"HIC","pop_m":1.4,  "gdp_b":23,  "fdi_b":1.4,"gfr":48.0,"rank":108,"tier":"MEDIUM", "macro":50,"policy":46,"digital":55,"human":44,"infra":48,"sustain":42,"internet_pct":78,"sectors":["D","K","C"]},
    {"iso3":"URY","iso2":"UY","name":"Uruguay",              "region":"LAC","income":"HIC","pop_m":3.5,  "gdp_b":72,  "fdi_b":2.8,"gfr":60.0,"rank":53,"tier":"MEDIUM", "macro":62,"policy":66,"digital":66,"human":58,"infra":58,"sustain":56,"internet_pct":82,"sectors":["K","C","D","L"]},
    {"iso3":"VCT","iso2":"VC","name":"St. Vincent & Grenadines","region":"LAC","income":"UMIC","pop_m":0.1,"gdp_b":1.0, "fdi_b":0.1,"gfr":40.0,"rank":140,"tier":"EMERGING","macro":42,"policy":40,"digital":44,"human":38,"infra":36,"sustain":40,"internet_pct":68,"sectors":["L","Q"]},
    {"iso3":"VEN","iso2":"VE","name":"Venezuela",            "region":"LAC","income":"UMIC","pop_m":32,   "gdp_b":95,  "fdi_b":0.2,"gfr":18.0,"rank":212,"tier":"DEVELOPING","macro":18,"policy":10,"digital":32,"human":36,"infra":18,"sustain":16,"internet_pct":72,"sectors":["D","B"]},

    # ── MIDDLE EAST & NORTH AFRICA ────────────────────────────────────────
    {"iso3":"ARE","iso2":"AE","name":"United Arab Emirates", "region":"MENA","income":"HIC","pop_m":10,   "gdp_b":504, "fdi_b":30.7,"gfr":80.0,"rank":3, "tier":"FRONTIER","macro":82,"policy":78,"digital":84,"human":54,"infra":92,"sustain":53,"internet_pct":99,"sectors":["K","J","L","H","D"]},
    {"iso3":"BHR","iso2":"BH","name":"Bahrain",              "region":"MENA","income":"HIC","pop_m":1.7,  "gdp_b":43,  "fdi_b":2.2,"gfr":66.0,"rank":32,"tier":"HIGH",   "macro":68,"policy":64,"digital":72,"human":48,"infra":74,"sustain":48,"internet_pct":98,"sectors":["K","J","D","L"]},
    {"iso3":"DJI","iso2":"DJ","name":"Djibouti",             "region":"MENA","income":"LMIC","pop_m":1.1,  "gdp_b":4.1, "fdi_b":0.4,"gfr":38.0,"rank":151,"tier":"EMERGING","macro":40,"policy":34,"digital":36,"human":30,"infra":44,"sustain":36,"internet_pct":52,"sectors":["H","D","L"]},
    {"iso3":"DZA","iso2":"DZ","name":"Algeria",              "region":"MENA","income":"LMIC","pop_m":45,   "gdp_b":195, "fdi_b":1.4,"gfr":40.0,"rank":141,"tier":"EMERGING","macro":44,"policy":34,"digital":42,"human":40,"infra":44,"sustain":36,"internet_pct":71,"sectors":["D","B","C"]},
    {"iso3":"EGY","iso2":"EG","name":"Egypt",                "region":"MENA","income":"LMIC","pop_m":105,  "gdp_b":395, "fdi_b":9.8,"gfr":52.4,"rank":85,"tier":"MEDIUM", "macro":55,"policy":48,"digital":52,"human":48,"infra":58,"sustain":42,"internet_pct":73,"sectors":["D","C","F","H"]},
    {"iso3":"IRN","iso2":"IR","name":"Iran",                 "region":"MENA","income":"LMIC","pop_m":87,   "gdp_b":368, "fdi_b":1.5,"gfr":30.0,"rank":175,"tier":"DEVELOPING","macro":34,"policy":18,"digital":38,"human":40,"infra":40,"sustain":22,"internet_pct":79,"sectors":["D","B","C"]},
    {"iso3":"IRQ","iso2":"IQ","name":"Iraq",                 "region":"MENA","income":"UMIC","pop_m":42,   "gdp_b":268, "fdi_b":3.2,"gfr":28.0,"rank":187,"tier":"DEVELOPING","macro":32,"policy":20,"digital":28,"human":28,"infra":32,"sustain":24,"internet_pct":74,"sectors":["D","B","F"]},
    {"iso3":"JOR","iso2":"JO","name":"Jordan",               "region":"MENA","income":"UMIC","pop_m":10,   "gdp_b":50,  "fdi_b":1.4,"gfr":52.0,"rank":92,"tier":"MEDIUM", "macro":52,"policy":50,"digital":58,"human":50,"infra":52,"sustain":46,"internet_pct":83,"sectors":["J","K","D","C"]},
    {"iso3":"KWT","iso2":"KW","name":"Kuwait",               "region":"MENA","income":"HIC","pop_m":4.3,  "gdp_b":162, "fdi_b":0.3,"gfr":58.0,"rank":65,"tier":"MEDIUM", "macro":65,"policy":54,"digital":68,"human":44,"infra":68,"sustain":42,"internet_pct":100,"sectors":["D","K","F"]},
    {"iso3":"LBN","iso2":"LB","name":"Lebanon",              "region":"MENA","income":"LMIC","pop_m":5.5,  "gdp_b":22,  "fdi_b":0.4,"gfr":28.0,"rank":190,"tier":"DEVELOPING","macro":24,"policy":18,"digital":40,"human":44,"infra":24,"sustain":24,"internet_pct":84,"sectors":["K","L"]},
    {"iso3":"LBY","iso2":"LY","name":"Libya",                "region":"MENA","income":"UMIC","pop_m":7.0,  "gdp_b":48,  "fdi_b":0.3,"gfr":22.0,"rank":207,"tier":"DEVELOPING","macro":24,"policy":14,"digital":22,"human":28,"infra":22,"sustain":18,"internet_pct":48,"sectors":["D","B"]},
    {"iso3":"MAR","iso2":"MA","name":"Morocco",              "region":"MENA","income":"LMIC","pop_m":37,   "gdp_b":138, "fdi_b":3.4,"gfr":50.0,"rank":97,"tier":"MEDIUM", "macro":52,"policy":50,"digital":52,"human":44,"infra":54,"sustain":46,"internet_pct":88,"sectors":["C","D","H","L"]},
    {"iso3":"MLT","iso2":"MT","name":"Malta",                "region":"ECA","income":"HIC","pop_m":0.5,  "gdp_b":19,  "fdi_b":8.2,"gfr":66.0,"rank":34,"tier":"HIGH",   "macro":68,"policy":68,"digital":74,"human":60,"infra":66,"sustain":58,"internet_pct":88,"sectors":["K","J","L"]},
    {"iso3":"MRT","iso2":"MR","name":"Mauritania",           "region":"MENA","income":"LMIC","pop_m":4.6,  "gdp_b":10,  "fdi_b":0.5,"gfr":30.0,"rank":176,"tier":"DEVELOPING","macro":32,"policy":26,"digital":26,"human":26,"infra":32,"sustain":28,"internet_pct":32,"sectors":["B","D","C"]},
    {"iso3":"OMN","iso2":"OM","name":"Oman",                 "region":"MENA","income":"HIC","pop_m":4.6,  "gdp_b":104, "fdi_b":3.2,"gfr":62.0,"rank":46,"tier":"MEDIUM", "macro":65,"policy":58,"digital":66,"human":46,"infra":70,"sustain":48,"internet_pct":96,"sectors":["D","L","H","K"]},
    {"iso3":"PSE","iso2":"PS","name":"West Bank and Gaza",   "region":"MENA","income":"LMIC","pop_m":5.3,  "gdp_b":17,  "fdi_b":0.1,"gfr":22.0,"rank":206,"tier":"DEVELOPING","macro":20,"policy":16,"digital":28,"human":30,"infra":18,"sustain":18,"internet_pct":72,"sectors":["C","Q"]},
    {"iso3":"QAT","iso2":"QA","name":"Qatar",                "region":"MENA","income":"HIC","pop_m":2.9,  "gdp_b":236, "fdi_b":5.2,"gfr":71.2,"rank":23,"tier":"HIGH",   "macro":74,"policy":66,"digital":76,"human":50,"infra":82,"sustain":58,"internet_pct":99,"sectors":["D","K","L","J"]},
    {"iso3":"SAU","iso2":"SA","name":"Saudi Arabia",         "region":"MENA","income":"HIC","pop_m":36,   "gdp_b":1069,"fdi_b":28.3,"gfr":68.1,"rank":9, "tier":"HIGH",   "macro":74,"policy":62,"digital":72,"human":48,"infra":76,"sustain":50,"internet_pct":98,"sectors":["D","K","F","J","L"]},
    {"iso3":"SYR","iso2":"SY","name":"Syrian Arab Republic", "region":"MENA","income":"LIC","pop_m":22,   "gdp_b":11,  "fdi_b":0.0,"gfr":10.0,"rank":214,"tier":"DEVELOPING","macro":10,"policy":6,"digital":14,"human":14,"infra":8,"sustain":8,"internet_pct":36,"sectors":["D","B"]},
    {"iso3":"TUN","iso2":"TN","name":"Tunisia",              "region":"MENA","income":"LMIC","pop_m":12,   "gdp_b":46,  "fdi_b":1.4,"gfr":44.0,"rank":124,"tier":"MEDIUM", "macro":44,"policy":42,"digital":50,"human":46,"infra":44,"sustain":40,"internet_pct":75,"sectors":["C","J","D","L"]},
    {"iso3":"YEM","iso2":"YE","name":"Yemen",                "region":"MENA","income":"LIC","pop_m":34,   "gdp_b":21,  "fdi_b":0.1,"gfr":12.0,"rank":213,"tier":"DEVELOPING","macro":12,"policy":8,"digital":14,"human":12,"infra":10,"sustain":12,"internet_pct":26,"sectors":["D","B"]},

    # ── NORTH AMERICA ─────────────────────────────────────────────────────
    {"iso3":"CAN","iso2":"CA","name":"Canada",               "region":"NAM","income":"HIC","pop_m":38,   "gdp_b":2140,"fdi_b":48.3,"gfr":83.1,"rank":6, "tier":"FRONTIER","macro":85,"policy":88,"digital":84,"human":76,"infra":82,"sustain":82,"internet_pct":95,"sectors":["B","D","K","J","C"]},
    {"iso3":"USA","iso2":"US","name":"United States",        "region":"NAM","income":"HIC","pop_m":335,  "gdp_b":27360,"fdi_b":285.0,"gfr":84.5,"rank":2, "tier":"FRONTIER","macro":89,"policy":83,"digital":91,"human":74,"infra":86,"sustain":68,"internet_pct":92,"sectors":["J","K","C","D","L"]},

    # ── SOUTH ASIA ────────────────────────────────────────────────────────
    {"iso3":"AFG","iso2":"AF","name":"Afghanistan",          "region":"SAS","income":"LIC","pop_m":42,   "gdp_b":15,  "fdi_b":0.0,"gfr":8.0,"rank":214,"tier":"DEVELOPING","macro":8,"policy":4,"digital":10,"human":8,"infra":8,"sustain":10,"internet_pct":18,"sectors":["B","D"]},
    {"iso3":"BGD","iso2":"BD","name":"Bangladesh",           "region":"SAS","income":"LMIC","pop_m":170,  "gdp_b":460, "fdi_b":3.2,"gfr":44.0,"rank":116,"tier":"MEDIUM", "macro":48,"policy":40,"digital":40,"human":40,"infra":42,"sustain":42,"internet_pct":44,"sectors":["C","D","H"]},
    {"iso3":"BTN","iso2":"BT","name":"Bhutan",               "region":"SAS","income":"LMIC","pop_m":0.8,  "gdp_b":2.8, "fdi_b":0.1,"gfr":42.0,"rank":130,"tier":"EMERGING","macro":44,"policy":46,"digital":38,"human":40,"infra":38,"sustain":48,"internet_pct":70,"sectors":["D","L","Q"]},
    {"iso3":"IND","iso2":"IN","name":"India",                "region":"SAS","income":"LMIC","pop_m":1429, "gdp_b":3730,"fdi_b":71.0,"gfr":62.3,"rank":10,"tier":"MEDIUM", "macro":68,"policy":56,"digital":59,"human":69,"infra":65,"sustain":38,"internet_pct":52,"sectors":["J","C","K","D","B"]},
    {"iso3":"LKA","iso2":"LK","name":"Sri Lanka",            "region":"SAS","income":"LMIC","pop_m":22,   "gdp_b":84,  "fdi_b":0.8,"gfr":44.0,"rank":114,"tier":"MEDIUM", "macro":44,"policy":38,"digital":48,"human":50,"infra":44,"sustain":42,"internet_pct":72,"sectors":["C","L","K","D"]},
    {"iso3":"MDV","iso2":"MV","name":"Maldives",             "region":"SAS","income":"UMIC","pop_m":0.5,  "gdp_b":6.9, "fdi_b":0.4,"gfr":48.0,"rank":109,"tier":"MEDIUM", "macro":50,"policy":48,"digital":60,"human":44,"infra":46,"sustain":42,"internet_pct":72,"sectors":["L","K","Q"]},
    {"iso3":"NPL","iso2":"NP","name":"Nepal",                "region":"SAS","income":"LMIC","pop_m":30,   "gdp_b":40,  "fdi_b":0.2,"gfr":34.0,"rank":166,"tier":"DEVELOPING","macro":36,"policy":30,"digital":32,"human":34,"infra":30,"sustain":36,"internet_pct":48,"sectors":["D","L","Q"]},
    {"iso3":"PAK","iso2":"PK","name":"Pakistan",             "region":"SAS","income":"LMIC","pop_m":230,  "gdp_b":338, "fdi_b":1.4,"gfr":36.0,"rank":153,"tier":"DEVELOPING","macro":38,"policy":30,"digital":36,"human":32,"infra":36,"sustain":34,"internet_pct":36,"sectors":["C","D","B","K"]},

    # ── SUB-SAHARAN AFRICA ────────────────────────────────────────────────
    {"iso3":"AGO","iso2":"AO","name":"Angola",               "region":"SSA","income":"LMIC","pop_m":35,   "gdp_b":93,  "fdi_b":3.8,"gfr":30.0,"rank":177,"tier":"DEVELOPING","macro":32,"policy":26,"digital":26,"human":24,"infra":28,"sustain":30,"internet_pct":33,"sectors":["D","B","C"]},
    {"iso3":"BDI","iso2":"BI","name":"Burundi",              "region":"SSA","income":"LIC","pop_m":13,   "gdp_b":3.1, "fdi_b":0.0,"gfr":16.0,"rank":211,"tier":"DEVELOPING","macro":16,"policy":12,"digital":12,"human":14,"infra":14,"sustain":20,"internet_pct":12,"sectors":["B","Q"]},
    {"iso3":"BEN","iso2":"BJ","name":"Benin",                "region":"SSA","income":"LMIC","pop_m":13,   "gdp_b":18,  "fdi_b":0.4,"gfr":28.0,"rank":189,"tier":"DEVELOPING","macro":30,"policy":26,"digital":24,"human":22,"infra":26,"sustain":30,"internet_pct":28,"sectors":["C","B","L"]},
    {"iso3":"BFA","iso2":"BF","name":"Burkina Faso",         "region":"SSA","income":"LIC","pop_m":22,   "gdp_b":19,  "fdi_b":0.3,"gfr":20.0,"rank":210,"tier":"DEVELOPING","macro":20,"policy":16,"digital":16,"human":14,"infra":18,"sustain":22,"internet_pct":20,"sectors":["B","C"]},
    {"iso3":"BWA","iso2":"BW","name":"Botswana",             "region":"SSA","income":"UMIC","pop_m":2.6,  "gdp_b":20,  "fdi_b":0.5,"gfr":44.0,"rank":112,"tier":"MEDIUM", "macro":46,"policy":50,"digital":42,"human":40,"infra":40,"sustain":42,"internet_pct":66,"sectors":["B","D","L"]},
    {"iso3":"CAF","iso2":"CF","name":"Central African Republic","region":"SSA","income":"LIC","pop_m":5.4, "gdp_b":2.7, "fdi_b":0.1,"gfr":12.0,"rank":212,"tier":"DEVELOPING","macro":12,"policy":8,"digital":10,"human":10,"infra":10,"sustain":16,"internet_pct":7,"sectors":["B","D"]},
    {"iso3":"CIV","iso2":"CI","name":"Côte d'Ivoire",        "region":"SSA","income":"LMIC","pop_m":27,   "gdp_b":71,  "fdi_b":1.0,"gfr":34.0,"rank":167,"tier":"DEVELOPING","macro":36,"policy":30,"digital":30,"human":26,"infra":34,"sustain":30,"internet_pct":36,"sectors":["C","B","D","H"]},
    {"iso3":"CMR","iso2":"CM","name":"Cameroon",             "region":"SSA","income":"LMIC","pop_m":28,   "gdp_b":45,  "fdi_b":0.6,"gfr":28.0,"rank":191,"tier":"DEVELOPING","macro":30,"policy":22,"digital":26,"human":24,"infra":28,"sustain":28,"internet_pct":36,"sectors":["B","D","C"]},
    {"iso3":"COD","iso2":"CD","name":"Dem. Rep. Congo",      "region":"SSA","income":"LIC","pop_m":100,  "gdp_b":64,  "fdi_b":1.8,"gfr":16.0,"rank":212,"tier":"DEVELOPING","macro":16,"policy":10,"digital":14,"human":12,"infra":14,"sustain":20,"internet_pct":18,"sectors":["B","D","C"]},
    {"iso3":"COG","iso2":"CG","name":"Congo, Rep.",          "region":"SSA","income":"LMIC","pop_m":5.8,  "gdp_b":15,  "fdi_b":1.4,"gfr":24.0,"rank":203,"tier":"DEVELOPING","macro":26,"policy":18,"digital":20,"human":20,"infra":22,"sustain":24,"internet_pct":28,"sectors":["D","B"]},
    {"iso3":"COM","iso2":"KM","name":"Comoros",              "region":"SSA","income":"LMIC","pop_m":0.9,  "gdp_b":1.4, "fdi_b":0.0,"gfr":22.0,"rank":207,"tier":"DEVELOPING","macro":22,"policy":18,"digital":18,"human":20,"infra":20,"sustain":26,"internet_pct":22,"sectors":["Q","L"]},
    {"iso3":"CPV","iso2":"CV","name":"Cabo Verde",           "region":"SSA","income":"LMIC","pop_m":0.6,  "gdp_b":2.3, "fdi_b":0.2,"gfr":44.0,"rank":113,"tier":"MEDIUM", "macro":46,"policy":48,"digital":44,"human":42,"infra":38,"sustain":44,"internet_pct":70,"sectors":["L","K","Q"]},
    {"iso3":"ERI","iso2":"ER","name":"Eritrea",              "region":"SSA","income":"LIC","pop_m":3.5,  "gdp_b":2.1, "fdi_b":0.1,"gfr":12.0,"rank":213,"tier":"DEVELOPING","macro":12,"policy":6,"digital":10,"human":12,"infra":10,"sustain":14,"internet_pct":8,"sectors":["B","D"]},
    {"iso3":"ETH","iso2":"ET","name":"Ethiopia",             "region":"SSA","income":"LIC","pop_m":126,  "gdp_b":156, "fdi_b":3.8,"gfr":30.0,"rank":178,"tier":"DEVELOPING","macro":34,"policy":26,"digital":22,"human":24,"infra":30,"sustain":28,"internet_pct":24,"sectors":["C","D","B","H"]},
    {"iso3":"GAB","iso2":"GA","name":"Gabon",                "region":"SSA","income":"UMIC","pop_m":2.4,  "gdp_b":20,  "fdi_b":0.8,"gfr":36.0,"rank":153,"tier":"DEVELOPING","macro":38,"policy":30,"digital":36,"human":32,"infra":36,"sustain":32,"internet_pct":62,"sectors":["D","B","C"]},
    {"iso3":"GHA","iso2":"GH","name":"Ghana",                "region":"SSA","income":"LMIC","pop_m":33,   "gdp_b":76,  "fdi_b":2.1,"gfr":44.0,"rank":111,"tier":"MEDIUM", "macro":46,"policy":44,"digital":40,"human":38,"infra":40,"sustain":42,"internet_pct":53,"sectors":["D","B","C","K"]},
    {"iso3":"GIN","iso2":"GN","name":"Guinea",               "region":"SSA","income":"LIC","pop_m":14,   "gdp_b":17,  "fdi_b":0.5,"gfr":20.0,"rank":211,"tier":"DEVELOPING","macro":22,"policy":16,"digital":16,"human":14,"infra":18,"sustain":22,"internet_pct":22,"sectors":["B","D"]},
    {"iso3":"GMB","iso2":"GM","name":"Gambia",               "region":"SSA","income":"LIC","pop_m":2.7,  "gdp_b":2.2, "fdi_b":0.1,"gfr":26.0,"rank":197,"tier":"DEVELOPING","macro":26,"policy":22,"digital":22,"human":22,"infra":22,"sustain":30,"internet_pct":30,"sectors":["Q","L","B"]},
    {"iso3":"GNB","iso2":"GW","name":"Guinea-Bissau",        "region":"SSA","income":"LIC","pop_m":2.1,  "gdp_b":1.7, "fdi_b":0.0,"gfr":18.0,"rank":213,"tier":"DEVELOPING","macro":18,"policy":14,"digital":14,"human":14,"infra":16,"sustain":20,"internet_pct":18,"sectors":["B","Q"]},
    {"iso3":"GNQ","iso2":"GQ","name":"Equatorial Guinea",    "region":"SSA","income":"UMIC","pop_m":1.5,  "gdp_b":12,  "fdi_b":0.5,"gfr":24.0,"rank":204,"tier":"DEVELOPING","macro":26,"policy":16,"digital":20,"human":20,"infra":24,"sustain":20,"internet_pct":48,"sectors":["D","B"]},
    {"iso3":"KEN","iso2":"KE","name":"Kenya",                "region":"SSA","income":"LMIC","pop_m":54,   "gdp_b":118, "fdi_b":1.8,"gfr":51.3,"rank":93,"tier":"MEDIUM", "macro":54,"policy":50,"digital":50,"human":44,"infra":48,"sustain":44,"internet_pct":58,"sectors":["J","K","D","C"]},
    {"iso3":"LBR","iso2":"LR","name":"Liberia",              "region":"SSA","income":"LIC","pop_m":5.4,  "gdp_b":4.0, "fdi_b":0.4,"gfr":22.0,"rank":208,"tier":"DEVELOPING","macro":22,"policy":18,"digital":18,"human":16,"infra":18,"sustain":26,"internet_pct":22,"sectors":["B","D"]},
    {"iso3":"LSO","iso2":"LS","name":"Lesotho",              "region":"SSA","income":"LMIC","pop_m":2.2,  "gdp_b":2.8, "fdi_b":0.2,"gfr":28.0,"rank":192,"tier":"DEVELOPING","macro":28,"policy":24,"digital":26,"human":26,"infra":24,"sustain":32,"internet_pct":38,"sectors":["C","D","Q"]},
    {"iso3":"MDG","iso2":"MG","name":"Madagascar",           "region":"SSA","income":"LIC","pop_m":29,   "gdp_b":15,  "fdi_b":0.5,"gfr":22.0,"rank":209,"tier":"DEVELOPING","macro":22,"policy":18,"digital":18,"human":16,"infra":18,"sustain":28,"internet_pct":20,"sectors":["C","B","D"]},
    {"iso3":"MLI","iso2":"ML","name":"Mali",                 "region":"SSA","income":"LIC","pop_m":23,   "gdp_b":19,  "fdi_b":0.4,"gfr":20.0,"rank":211,"tier":"DEVELOPING","macro":20,"policy":14,"digital":16,"human":14,"infra":18,"sustain":22,"internet_pct":28,"sectors":["B","D","C"]},
    {"iso3":"MOZ","iso2":"MZ","name":"Mozambique",           "region":"SSA","income":"LIC","pop_m":33,   "gdp_b":18,  "fdi_b":2.4,"gfr":24.0,"rank":202,"tier":"DEVELOPING","macro":24,"policy":20,"digital":18,"human":16,"infra":22,"sustain":28,"internet_pct":21,"sectors":["D","B","C"]},
    {"iso3":"MUS","iso2":"MU","name":"Mauritius",            "region":"SSA","income":"HIC","pop_m":1.3,  "gdp_b":14,  "fdi_b":0.5,"gfr":62.0,"rank":43,"tier":"MEDIUM", "macro":64,"policy":66,"digital":66,"human":56,"infra":60,"sustain":58,"internet_pct":74,"sectors":["K","L","J","Q"]},
    {"iso3":"MWI","iso2":"MW","name":"Malawi",               "region":"SSA","income":"LIC","pop_m":20,   "gdp_b":13,  "fdi_b":0.2,"gfr":20.0,"rank":210,"tier":"DEVELOPING","macro":20,"policy":16,"digital":14,"human":14,"infra":16,"sustain":24,"internet_pct":14,"sectors":["C","B","Q"]},
    {"iso3":"NAM","iso2":"NA","name":"Namibia",              "region":"SSA","income":"UMIC","pop_m":2.7,  "gdp_b":13,  "fdi_b":0.5,"gfr":44.0,"rank":110,"tier":"MEDIUM", "macro":46,"policy":48,"digital":44,"human":38,"infra":42,"sustain":44,"internet_pct":56,"sectors":["B","D","L"]},
    {"iso3":"NER","iso2":"NE","name":"Niger",                "region":"SSA","income":"LIC","pop_m":25,   "gdp_b":15,  "fdi_b":0.5,"gfr":16.0,"rank":212,"tier":"DEVELOPING","macro":16,"policy":12,"digital":12,"human":8,"infra":14,"sustain":18,"internet_pct":14,"sectors":["B","D"]},
    {"iso3":"NGA","iso2":"NG","name":"Nigeria",              "region":"SSA","income":"LMIC","pop_m":218,  "gdp_b":477, "fdi_b":4.1,"gfr":42.1,"rank":125,"tier":"EMERGING","macro":46,"policy":36,"digital":42,"human":40,"infra":36,"sustain":36,"internet_pct":55,"sectors":["D","B","C","K","J"]},
    {"iso3":"RWA","iso2":"RW","name":"Rwanda",               "region":"SSA","income":"LIC","pop_m":14,   "gdp_b":14,  "fdi_b":0.4,"gfr":44.0,"rank":111,"tier":"MEDIUM", "macro":46,"policy":52,"digital":40,"human":38,"infra":40,"sustain":44,"internet_pct":52,"sectors":["J","K","D","L"]},
    {"iso3":"SDN","iso2":"SD","name":"Sudan",                "region":"SSA","income":"LIC","pop_m":46,   "gdp_b":35,  "fdi_b":0.5,"gfr":18.0,"rank":213,"tier":"DEVELOPING","macro":18,"policy":10,"digital":18,"human":14,"infra":14,"sustain":16,"internet_pct":28,"sectors":["B","D","C"]},
    {"iso3":"SEN","iso2":"SN","name":"Senegal",              "region":"SSA","income":"LMIC","pop_m":17,   "gdp_b":27,  "fdi_b":1.4,"gfr":36.0,"rank":156,"tier":"DEVELOPING","macro":38,"policy":36,"digital":34,"human":30,"infra":34,"sustain":36,"internet_pct":46,"sectors":["B","D","C","L"]},
    {"iso3":"SLE","iso2":"SL","name":"Sierra Leone",         "region":"SSA","income":"LIC","pop_m":8.4,  "gdp_b":4.6, "fdi_b":0.4,"gfr":20.0,"rank":211,"tier":"DEVELOPING","macro":20,"policy":16,"digital":16,"human":12,"infra":16,"sustain":22,"internet_pct":22,"sectors":["B","D","Q"]},
    {"iso3":"SOM","iso2":"SO","name":"Somalia",              "region":"SSA","income":"LIC","pop_m":18,   "gdp_b":7.6, "fdi_b":0.1,"gfr":10.0,"rank":214,"tier":"DEVELOPING","macro":10,"policy":6,"digital":10,"human":8,"infra":8,"sustain":10,"internet_pct":18,"sectors":["B","D"]},
    {"iso3":"SSD","iso2":"SS","name":"South Sudan",          "region":"SSA","income":"LIC","pop_m":11,   "gdp_b":7.5, "fdi_b":0.3,"gfr":10.0,"rank":214,"tier":"DEVELOPING","macro":10,"policy":6,"digital":8,"human":8,"infra":8,"sustain":10,"internet_pct":8,"sectors":["D","B"]},
    {"iso3":"STP","iso2":"ST","name":"São Tomé and Príncipe","region":"SSA","income":"LMIC","pop_m":0.2,  "gdp_b":0.5, "fdi_b":0.0,"gfr":28.0,"rank":193,"tier":"DEVELOPING","macro":28,"policy":26,"digital":26,"human":24,"infra":22,"sustain":34,"internet_pct":32,"sectors":["Q","L"]},
    {"iso3":"SWZ","iso2":"SZ","name":"Eswatini",             "region":"SSA","income":"LMIC","pop_m":1.2,  "gdp_b":4.8, "fdi_b":0.1,"gfr":30.0,"rank":180,"tier":"Developing","macro":30,"policy":26,"digital":26,"human":26,"infra":28,"sustain":30,"internet_pct":47,"sectors":["C","D","L"]},
    {"iso3":"TCD","iso2":"TD","name":"Chad",                 "region":"SSA","income":"LIC","pop_m":18,   "gdp_b":12,  "fdi_b":0.5,"gfr":14.0,"rank":213,"tier":"DEVELOPING","macro":14,"policy":10,"digital":10,"human":10,"infra":12,"sustain":16,"internet_pct":14,"sectors":["D","B"]},
    {"iso3":"TGO","iso2":"TG","name":"Togo",                 "region":"SSA","income":"LIC","pop_m":8.7,  "gdp_b":8.1, "fdi_b":0.4,"gfr":28.0,"rank":194,"tier":"DEVELOPING","macro":28,"policy":24,"digital":24,"human":20,"infra":26,"sustain":30,"internet_pct":28,"sectors":["B","H","L"]},
    {"iso3":"TZA","iso2":"TZ","name":"Tanzania",             "region":"SSA","income":"LMIC","pop_m":64,   "gdp_b":79,  "fdi_b":1.2,"gfr":36.0,"rank":154,"tier":"DEVELOPING","macro":38,"policy":34,"digital":30,"human":28,"infra":34,"sustain":38,"internet_pct":28,"sectors":["D","B","C","L"]},
    {"iso3":"UGA","iso2":"UG","name":"Uganda",               "region":"SSA","income":"LIC","pop_m":48,   "gdp_b":45,  "fdi_b":0.8,"gfr":30.0,"rank":179,"tier":"DEVELOPING","macro":32,"policy":28,"digital":24,"human":22,"infra":26,"sustain":32,"internet_pct":26,"sectors":["D","B","C"]},
    {"iso3":"ZAF","iso2":"ZA","name":"South Africa",         "region":"SSA","income":"UMIC","pop_m":60,   "gdp_b":373, "fdi_b":5.4,"gfr":51.3,"rank":94,"tier":"MEDIUM", "macro":52,"policy":52,"digital":55,"human":46,"infra":52,"sustain":42,"internet_pct":72,"sectors":["D","K","B","C","J"]},
    {"iso3":"ZMB","iso2":"ZM","name":"Zambia",               "region":"SSA","income":"LMIC","pop_m":20,   "gdp_b":29,  "fdi_b":1.0,"gfr":30.0,"rank":181,"tier":"Developing","macro":30,"policy":26,"digital":24,"human":22,"infra":28,"sustain":32,"internet_pct":26,"sectors":["B","D","C"]},
    {"iso3":"ZWE","iso2":"ZW","name":"Zimbabwe",             "region":"SSA","income":"LMIC","pop_m":16,   "gdp_b":26,  "fdi_b":0.4,"gfr":26.0,"rank":196,"tier":"DEVELOPING","macro":26,"policy":20,"digital":26,"human":26,"infra":22,"sustain":24,"internet_pct":34,"sectors":["B","D","C"]},
]

# ── 21 ISIC SECTORS ───────────────────────────────────────────────────────
ALL_SECTORS = [
    {"code":"A","name":"Agriculture, Forestry & Fishing",       "fdi_weight":2.1,  "signal_volume":"LOW"},
    {"code":"B","name":"Mining & Quarrying",                    "fdi_weight":8.4,  "signal_volume":"MEDIUM"},
    {"code":"C","name":"Manufacturing",                         "fdi_weight":18.2, "signal_volume":"HIGH"},
    {"code":"D","name":"Electricity, Gas & Energy",             "fdi_weight":12.8, "signal_volume":"HIGH"},
    {"code":"E","name":"Water Supply & Waste Management",       "fdi_weight":1.8,  "signal_volume":"LOW"},
    {"code":"F","name":"Construction",                          "fdi_weight":4.2,  "signal_volume":"MEDIUM"},
    {"code":"G","name":"Wholesale & Retail Trade",              "fdi_weight":3.8,  "signal_volume":"MEDIUM"},
    {"code":"H","name":"Transportation & Logistics",            "fdi_weight":6.4,  "signal_volume":"MEDIUM"},
    {"code":"I","name":"Accommodation & Food Services",         "fdi_weight":2.4,  "signal_volume":"LOW"},
    {"code":"J","name":"Information & Communication Technology","fdi_weight":22.4, "signal_volume":"PLATINUM"},
    {"code":"K","name":"Financial & Insurance Services",        "fdi_weight":14.8, "signal_volume":"HIGH"},
    {"code":"L","name":"Real Estate",                           "fdi_weight":8.2,  "signal_volume":"MEDIUM"},
    {"code":"M","name":"Professional & Scientific Services",    "fdi_weight":3.4,  "signal_volume":"MEDIUM"},
    {"code":"N","name":"Administrative & Support Services",     "fdi_weight":1.8,  "signal_volume":"LOW"},
    {"code":"O","name":"Public Administration & Defence",       "fdi_weight":0.8,  "signal_volume":"LOW"},
    {"code":"P","name":"Education",                             "fdi_weight":1.2,  "signal_volume":"LOW"},
    {"code":"Q","name":"Health & Social Work",                  "fdi_weight":2.4,  "signal_volume":"LOW"},
    {"code":"R","name":"Arts, Entertainment & Recreation",      "fdi_weight":0.8,  "signal_volume":"LOW"},
    {"code":"S","name":"Other Service Activities",              "fdi_weight":0.6,  "signal_volume":"LOW"},
    {"code":"T","name":"Household Activities",                  "fdi_weight":0.1,  "signal_volume":"LOW"},
    {"code":"U","name":"Extraterritorial Organisations",        "fdi_weight":0.2,  "signal_volume":"LOW"},
]

# ── 20 DATA SOURCES (internal registry, not public-facing) ───────────────
INTERNAL_SOURCES = [
    # T1: International Organisations
    {"id":"S001","name":"IMF World Economic Outlook","org":"IMF","tier":"T1","type":"IO","freq":"Biannual","coverage":215,"premium":False,"api_url":"https://www.imf.org/external/datamapper/api/v1/"},
    {"id":"S002","name":"World Bank World Development Indicators","org":"World Bank","tier":"T1","type":"IO","freq":"Annual","coverage":217,"premium":False,"api_url":"https://api.worldbank.org/v2/"},
    {"id":"S003","name":"UNCTAD Investment Statistics","org":"UNCTAD","tier":"T1","type":"IO","freq":"Annual","coverage":196,"premium":False,"api_url":"https://unctadstat.unctad.org/"},
    {"id":"S004","name":"ILO STAT","org":"ILO","tier":"T1","type":"IO","freq":"Annual","coverage":189,"premium":False,"api_url":"https://ilostat.ilo.org/data/"},
    {"id":"S005","name":"IEA Energy Statistics","org":"IEA","tier":"T1","type":"IO","freq":"Annual","coverage":150,"premium":False,"api_url":"https://www.iea.org/data-and-statistics/"},
    {"id":"S006","name":"IRENA Renewable Energy","org":"IRENA","tier":"T1","type":"IO","freq":"Annual","coverage":170,"premium":False,"api_url":"https://www.irena.org/Data"},
    {"id":"S007","name":"WTO Statistics Portal","org":"WTO","tier":"T1","type":"IO","freq":"Annual","coverage":164,"premium":False,"api_url":"https://data.wto.org/"},
    {"id":"S008","name":"OECD Data Portal","org":"OECD","tier":"T1","type":"IO","freq":"Quarterly","coverage":38,"premium":False,"api_url":"https://stats.oecd.org/"},
    {"id":"S009","name":"UN Comtrade","org":"UN","tier":"T1","type":"IO","freq":"Monthly","coverage":200,"premium":False,"api_url":"https://comtradeplus.un.org/"},
    {"id":"S010","name":"Federal Reserve FRED","org":"US Fed","tier":"T1","type":"CENTRAL_BANK","freq":"Daily","coverage":1,"premium":False,"api_url":"https://fred.stlouisfed.org/"},
    # T4: NGO & Research
    {"id":"S011","name":"Transparency International CPI","org":"TI","tier":"T4","type":"NGO","freq":"Annual","coverage":180,"premium":False,"api_url":"https://www.transparency.org/"},
    {"id":"S012","name":"Freedom House","org":"FH","tier":"T4","type":"NGO","freq":"Annual","coverage":210,"premium":False,"api_url":"https://freedomhouse.org/"},
    {"id":"S013","name":"World Justice Project","org":"WJP","tier":"T4","type":"NGO","freq":"Annual","coverage":140,"premium":False,"api_url":"https://worldjusticeproject.org/"},
    # T6: Media/News
    {"id":"S014","name":"GDELT News Intelligence","org":"GDELT","tier":"T6","type":"MEDIA","freq":"15min","coverage":215,"premium":False,"api_url":"https://api.gdeltproject.org/"},
    # National/Government
    {"id":"S015","name":"UAE Federal Statistics Centre","org":"FCSA","tier":"T1","type":"GOVERNMENT","freq":"Quarterly","coverage":1,"premium":False,"api_url":"https://fcsa.gov.ae/"},
    {"id":"S016","name":"GASTAT Saudi Arabia","org":"GASTAT","tier":"T1","type":"GOVERNMENT","freq":"Quarterly","coverage":1,"premium":False,"api_url":"https://www.stats.gov.sa/"},
    # Premium (future)
    {"id":"S017","name":"Bloomberg Terminal API","org":"Bloomberg","tier":"T3","type":"COMMERCIAL","freq":"Realtime","coverage":215,"premium":True,"api_url":None},
    {"id":"S018","name":"fDi Markets (Financial Times)","org":"FT","tier":"T4","type":"COMMERCIAL","freq":"Daily","coverage":215,"premium":True,"api_url":None},
    {"id":"S019","name":"Oxford Economics","org":"OE","tier":"T4","type":"COMMERCIAL","freq":"Monthly","coverage":200,"premium":True,"api_url":None},
    {"id":"S020","name":"PitchBook","org":"PitchBook","tier":"T4","type":"COMMERCIAL","freq":"Daily","coverage":215,"premium":True,"api_url":None},
]

if __name__ == "__main__":
    print(f"Economies: {len(ALL_215_ECONOMIES)}")
    print(f"Sectors: {len(ALL_SECTORS)}")
    print(f"Sources: {len(INTERNAL_SOURCES)}")
    by_region = {}
    for e in ALL_215_ECONOMIES:
        by_region[e['region']] = by_region.get(e['region'],0)+1
    for r,c in sorted(by_region.items()):
        print(f"  {r}: {c}")

# ── ADDITIONAL ECONOMIES TO REACH 215 ────────────────────────────────────
ADDITIONAL_ECONOMIES = [
    # MENA remaining
    {"iso3":"ISR","iso2":"IL","name":"Israel",               "region":"MENA","income":"HIC","pop_m":9.7, "gdp_b":522, "fdi_b":24.2,"gfr":72.0,"rank":21,"tier":"HIGH","macro":74,"policy":70,"digital":78,"human":68,"infra":72,"sustain":68,"internet_pct":92,"sectors":["J","K","C","D"]},
    # ECA remaining
    {"iso3":"AND","iso2":"AD","name":"Andorra",              "region":"ECA","income":"HIC","pop_m":0.08,"gdp_b":3.3, "fdi_b":0.5,"gfr":62.0,"rank":45,"tier":"MEDIUM","macro":64,"policy":66,"digital":70,"human":58,"infra":62,"sustain":60,"internet_pct":98,"sectors":["K","L","J"]},
    {"iso3":"MCO","iso2":"MC","name":"Monaco",               "region":"ECA","income":"HIC","pop_m":0.04,"gdp_b":7.7, "fdi_b":1.2,"gfr":72.0,"rank":20,"tier":"HIGH","macro":74,"policy":72,"digital":76,"human":66,"infra":78,"sustain":68,"internet_pct":99,"sectors":["K","L","J"]},
    {"iso3":"SMR","iso2":"SM","name":"San Marino",           "region":"ECA","income":"HIC","pop_m":0.03,"gdp_b":1.8, "fdi_b":0.2,"gfr":62.0,"rank":44,"tier":"MEDIUM","macro":64,"policy":66,"digital":70,"human":60,"infra":62,"sustain":60,"internet_pct":98,"sectors":["K","J","C"]},
    # SSA remaining
    {"iso3":"DJI","iso2":"DJ","name":"Djibouti",             "region":"SSA","income":"LMIC","pop_m":1.1, "gdp_b":4.1, "fdi_b":0.4,"gfr":38.0,"rank":151,"tier":"EMERGING","macro":40,"policy":34,"digital":36,"human":30,"infra":44,"sustain":36,"internet_pct":52,"sectors":["H","D","L"]},
    # Additional SAS
    {"iso3":"PRK","iso2":"KP","name":"North Korea",          "region":"EAP","income":"LIC","pop_m":26,  "gdp_b":17,  "fdi_b":0.0,"gfr":8.0,"rank":215,"tier":"DEVELOPING","macro":10,"policy":4,"digital":8,"human":14,"infra":12,"sustain":8,"internet_pct":0,"sectors":["B","C"]},
    # Additional MENA
    {"iso3":"CPV","iso2":"CV","name":"Cabo Verde",           "region":"SSA","income":"LMIC","pop_m":0.6, "gdp_b":2.3, "fdi_b":0.2,"gfr":44.0,"rank":113,"tier":"MEDIUM","macro":46,"policy":48,"digital":44,"human":42,"infra":38,"sustain":44,"internet_pct":70,"sectors":["L","K","Q"]},
    # Remaining small states
    {"iso3":"FSM","iso2":"FM","name":"Micronesia",           "region":"EAP","income":"LMIC","pop_m":0.1, "gdp_b":0.4, "fdi_b":0.0,"gfr":24.0,"rank":203,"tier":"DEVELOPING","macro":24,"policy":20,"digital":20,"human":26,"infra":18,"sustain":28,"internet_pct":40,"sectors":["Q","L"]},
    {"iso3":"GUM","iso2":"GU","name":"Guam",                 "region":"EAP","income":"HIC","pop_m":0.2, "gdp_b":6.1, "fdi_b":0.2,"gfr":48.0,"rank":100,"tier":"MEDIUM","macro":50,"policy":48,"digital":55,"human":44,"infra":48,"sustain":44,"internet_pct":85,"sectors":["L","H","Q"]},
    {"iso3":"NCL","iso2":"NC","name":"New Caledonia",        "region":"EAP","income":"HIC","pop_m":0.3, "gdp_b":9.9, "fdi_b":0.8,"gfr":55.0,"rank":76,"tier":"MEDIUM","macro":56,"policy":54,"digital":58,"human":50,"infra":56,"sustain":56,"internet_pct":82,"sectors":["B","L","D"]},
    {"iso3":"PYF","iso2":"PF","name":"French Polynesia",     "region":"EAP","income":"HIC","pop_m":0.3, "gdp_b":5.4, "fdi_b":0.2,"gfr":52.0,"rank":89,"tier":"MEDIUM","macro":54,"policy":52,"digital":58,"human":48,"infra":52,"sustain":52,"internet_pct":76,"sectors":["L","K","Q"]},
    {"iso3":"XKX","iso2":"XK","name":"Kosovo",               "region":"ECA","income":"UMIC","pop_m":1.8, "gdp_b":10,  "fdi_b":0.4,"gfr":36.0,"rank":156,"tier":"DEVELOPING","macro":38,"policy":34,"digital":42,"human":36,"infra":32,"sustain":34,"internet_pct":76,"sectors":["C","L"]},
    {"iso3":"GIB","iso2":"GI","name":"Gibraltar",            "region":"ECA","income":"HIC","pop_m":0.04,"gdp_b":2.6, "fdi_b":0.5,"gfr":64.0,"rank":38,"tier":"HIGH","macro":66,"policy":66,"digital":72,"human":60,"infra":66,"sustain":58,"internet_pct":98,"sectors":["K","J","L"]},
    {"iso3":"FRO","iso2":"FO","name":"Faroe Islands",        "region":"ECA","income":"HIC","pop_m":0.05,"gdp_b":3.8, "fdi_b":0.1,"gfr":62.0,"rank":43,"tier":"MEDIUM","macro":64,"policy":64,"digital":72,"human":58,"infra":62,"sustain":68,"internet_pct":98,"sectors":["C","D","K"]},
    {"iso3":"GRL","iso2":"GL","name":"Greenland",            "region":"NAM","income":"HIC","pop_m":0.06,"gdp_b":3.2, "fdi_b":0.0,"gfr":52.0,"rank":87,"tier":"MEDIUM","macro":54,"policy":56,"digital":60,"human":50,"infra":48,"sustain":62,"internet_pct":72,"sectors":["B","D","L"]},
    {"iso3":"CUW","iso2":"CW","name":"Curaçao",              "region":"LAC","income":"HIC","pop_m":0.2, "gdp_b":2.9, "fdi_b":0.5,"gfr":52.0,"rank":88,"tier":"MEDIUM","macro":54,"policy":52,"digital":58,"human":48,"infra":52,"sustain":46,"internet_pct":80,"sectors":["K","L","H"]},
    {"iso3":"ABW","iso2":"AW","name":"Aruba",                "region":"LAC","income":"HIC","pop_m":0.1, "gdp_b":3.4, "fdi_b":0.3,"gfr":52.0,"rank":90,"tier":"MEDIUM","macro":54,"policy":52,"digital":58,"human":48,"infra":52,"sustain":46,"internet_pct":84,"sectors":["L","K","H"]},
    {"iso3":"BMU","iso2":"BM","name":"Bermuda",              "region":"NAM","income":"HIC","pop_m":0.06,"gdp_b":7.6, "fdi_b":2.1,"gfr":62.0,"rank":42,"tier":"MEDIUM","macro":64,"policy":64,"digital":70,"human":58,"infra":62,"sustain":58,"internet_pct":98,"sectors":["K","L","J"]},
    {"iso3":"CYM","iso2":"KY","name":"Cayman Islands",       "region":"LAC","income":"HIC","pop_m":0.07,"gdp_b":6.4, "fdi_b":1.8,"gfr":62.0,"rank":43,"tier":"MEDIUM","macro":64,"policy":62,"digital":68,"human":56,"infra":62,"sustain":52,"internet_pct":92,"sectors":["K","L","J"]},
    {"iso3":"IMN","iso2":"IM","name":"Isle of Man",          "region":"ECA","income":"HIC","pop_m":0.08,"gdp_b":6.8, "fdi_b":0.8,"gfr":64.0,"rank":37,"tier":"HIGH","macro":66,"policy":68,"digital":72,"human":62,"infra":64,"sustain":60,"internet_pct":98,"sectors":["K","J","L"]},
    {"iso3":"JEY","iso2":"JE","name":"Jersey",               "region":"ECA","income":"HIC","pop_m":0.1, "gdp_b":5.1, "fdi_b":1.4,"gfr":66.0,"rank":33,"tier":"HIGH","macro":68,"policy":70,"digital":72,"human":62,"infra":66,"sustain":62,"internet_pct":98,"sectors":["K","J","L"]},
    {"iso3":"GGY","iso2":"GG","name":"Guernsey",             "region":"ECA","income":"HIC","pop_m":0.07,"gdp_b":3.5, "fdi_b":0.8,"gfr":65.0,"rank":36,"tier":"HIGH","macro":67,"policy":70,"digital":72,"human":61,"infra":66,"sustain":62,"internet_pct":98,"sectors":["K","J","L"]},
    {"iso3":"MNP","iso2":"MP","name":"Northern Mariana Islands","region":"EAP","income":"HIC","pop_m":0.06,"gdp_b":1.2,"fdi_b":0.1,"gfr":38.0,"rank":148,"tier":"EMERGING","macro":40,"policy":38,"digital":44,"human":36,"infra":36,"sustain":38,"internet_pct":74,"sectors":["L","Q"]},
    {"iso3":"SXM","iso2":"SX","name":"Sint Maarten",         "region":"LAC","income":"HIC","pop_m":0.04,"gdp_b":1.3, "fdi_b":0.2,"gfr":44.0,"rank":116,"tier":"MEDIUM","macro":46,"policy":44,"digital":50,"human":40,"infra":44,"sustain":40,"internet_pct":82,"sectors":["L","K","H"]},
]

ALL_215_ECONOMIES.extend(ADDITIONAL_ECONOMIES)

if __name__ == "__main__":
    print(f"\nFINAL COUNT: {len(ALL_215_ECONOMIES)} economies")
    by_region = {}
    for e in ALL_215_ECONOMIES:
        r = e.get('region','?')
        by_region[r] = by_region.get(r,0)+1
    for r,c in sorted(by_region.items()):
        print(f"  {r}: {c}")
    print(f"Sectors: {len(ALL_SECTORS)}")
    print(f"Sources: {len(INTERNAL_SOURCES)}")
