'use client';
import { useState, useEffect } from 'react';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import Link from 'next/link';
import { Activity, Users, FileText, Zap, TrendingUp, Globe, Bell } from 'lucide-react';

const STATS = [
  {l:'Active Subscribers',v:'12,847',d:'+124 this week',c:'#00ffc8',icon:<Users size={14} color="#00ffc8"/>},
  {l:'Reports Generated',v:'3,241',d:'+48 today',c:'#00d4ff',icon:<FileText size={14} color="#00d4ff"/>},
  {l:'Signals Processed',v:'1,847',d:'Last 7 days',c:'#ffd700',icon:<Zap size={14} color="#ffd700"/>},
  {l:'Economies Tracked',v:'215',d:'Weekly GOSA updates',c:'#9b59b6',icon:<Globe size={14} color="#9b59b6"/>},
  {l:'API Calls Today',v:'48,291',d:'+12% vs yesterday',c:'#e67e22',icon:<Activity size={14} color="#e67e22"/>},
  {l:'Newsletter Open Rate',v:'41.2%',d:'+2.1% vs last issue',c:'#00ffc8',icon:<Bell size={14} color="#00ffc8"/>},
];
const AGENTS = [
  {id:'AGT-01',name:'Data Collection',    status:'ACTIVE',last:'2m ago',signals:29,uptime:'99.8%'},
  {id:'AGT-02',name:'Signal Detection',   status:'ACTIVE',last:'2m ago',signals:28,uptime:'99.6%'},
  {id:'AGT-03',name:'Verification',       status:'ACTIVE',last:'2m ago',signals:28,uptime:'99.4%'},
  {id:'AGT-04',name:'GOSA Scoring',       status:'ACTIVE',last:'5m ago',signals:15,uptime:'99.9%'},
  {id:'AGT-05',name:'GFR Ranking',        status:'ACTIVE',last:'10m ago',signals:15,uptime:'99.7%'},
  {id:'AGT-06',name:'Newsletter',         status:'IDLE',  last:'6d ago',signals:1, uptime:'100%'},
];
const ACTIVITY = [
  {t:'2m ago',a:'AGT-02 detected PLATINUM signal: Malaysia FDI cap lifted',type:'signal'},
  {t:'8m ago',a:'User trial expired — upgrade prompt triggered',type:'trial'},
  {t:'14m ago',a:'Report generated: Vietnam EV Battery Analysis (3 pages)',type:'report'},
  {t:'22m ago',a:'New subscriber: m.hassan@misa.gov.sa — Professional trial',type:'user'},
  {t:'31m ago',a:'AGT-04 GOSA update: Singapore +0.3pts, UAE +1.2pts',type:'score'},
  {t:'45m ago',a:'Newsletter Issue #47 generated by AGT-06 — awaiting review',type:'newsletter'},
  {t:'1h ago',a:'API rate limit: 1 user at 94% of daily quota',type:'api'},
  {t:'2h ago',a:'Report downloaded: Thailand EV Analysis (trial user)',type:'report'},
];

export default function AdminPage(){
  const [time,setTime]=useState(new Date());
  useEffect(()=>{const iv=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(iv);},[]);

  const tc:Record<string,string>={signal:'#00ffc8',trial:'#ffd700',report:'#00d4ff',user:'#9b59b6',score:'#e67e22',newsletter:'#00ffc8',api:'#ff4466'};

  return(
    <div style={{minHeight:'100vh',background:'#020c14',fontFamily:"'Inter','Helvetica Neue',sans-serif"}}>
      <NavBar/>
      <div style={{background:'linear-gradient(135deg,#020c14,#060f1a)',padding:'18px 24px',borderBottom:'1px solid rgba(0,255,200,0.06)',position:'relative',overflow:'hidden'}}>
        <div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(rgba(0,255,200,0.02) 1px,transparent 1px),linear-gradient(90deg,rgba(0,255,200,0.02) 1px,transparent 1px)',backgroundSize:'64px 64px',pointerEvents:'none'}}/>
        <div style={{maxWidth:'1540px',margin:'0 auto',display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:'12px',position:'relative'}}>
          <div>
            <div style={{fontSize:'10px',fontWeight:800,color:'rgba(0,255,200,0.5)',letterSpacing:'0.2em',marginBottom:'4px',fontFamily:"'Orbitron','Inter',sans-serif"}}>ADMIN DASHBOARD</div>
            <h1 style={{fontSize:'20px',fontWeight:900,color:'#e8f4f8'}}>Platform Operations Center</h1>
          </div>
          <div style={{display:'flex',gap:'10px',alignItems:'center'}}>
            <div style={{fontSize:'16px',fontWeight:800,color:'#00ffc8',fontFamily:"'JetBrains Mono',monospace",padding:'6px 14px',background:'rgba(0,255,200,0.05)',border:'1px solid rgba(0,255,200,0.12)',borderRadius:'8px'}}>{time.toLocaleTimeString()}</div>
            <Link href="/newsletter" style={{padding:'7px 14px',background:'rgba(0,255,200,0.08)',border:'1px solid rgba(0,255,200,0.2)',borderRadius:'8px',textDecoration:'none',fontSize:'12px',fontWeight:700,color:'#00ffc8'}}>Newsletter Admin →</Link>
          </div>
        </div>
      </div>

      <div style={{maxWidth:'1540px',margin:'0 auto',padding:'20px 24px'}}>
        {/* Stats */}
        <div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:'10px',marginBottom:'16px'}}>
          {STATS.map(({l,v,d,c,icon})=>(
            <div key={l} style={{padding:'18px',background:'rgba(10,22,40,0.7)',border:'1px solid rgba(0,180,216,0.08)',borderRadius:'12px',borderTop:`2px solid ${c}`}}>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'8px'}}><span style={{fontSize:'9px',color:'rgba(232,244,248,0.3)',textTransform:'uppercase',letterSpacing:'0.06em'}}>{l}</span>{icon}</div>
              <div style={{fontSize:'22px',fontWeight:900,color:c,fontFamily:"'JetBrains Mono',monospace",textShadow:`0 0 12px ${c}40`}}>{v}</div>
              <div style={{fontSize:'10px',color:'rgba(232,244,248,0.3)',marginTop:'3px'}}>{d}</div>
            </div>
          ))}
        </div>

        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'16px',marginBottom:'16px'}}>
          {/* Agent pipeline */}
          <div style={{background:'rgba(10,22,40,0.7)',border:'1px solid rgba(0,180,216,0.1)',borderRadius:'12px',overflow:'hidden'}}>
            <div style={{padding:'12px 18px',borderBottom:'1px solid rgba(0,255,200,0.06)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'rgba(0,0,0,0.2)'}}>
              <span style={{fontSize:'11px',fontWeight:800,color:'rgba(232,244,248,0.7)',letterSpacing:'0.08em',textTransform:'uppercase',fontFamily:"'Orbitron','Inter',sans-serif"}}>AI Agent Pipeline</span>
              <span style={{fontSize:'8px',fontWeight:800,padding:'2px 8px',borderRadius:'4px',background:'rgba(0,255,200,0.08)',color:'#00ffc8',letterSpacing:'0.08em',fontFamily:"'JetBrains Mono',monospace"}}>ALL ACTIVE</span>
            </div>
            {AGENTS.map(ag=>(
              <div key={ag.id} style={{padding:'11px 18px',borderBottom:'1px solid rgba(255,255,255,0.025)',display:'flex',alignItems:'center',gap:'12px'}}>
                <div style={{width:'7px',height:'7px',borderRadius:'50%',background:ag.status==='ACTIVE'?'#00ffc8':'#ffd700',boxShadow:`0 0 6px ${ag.status==='ACTIVE'?'#00ffc8':'#ffd700'}`,flexShrink:0}}/>
                <div style={{flex:1}}>
                  <div style={{fontSize:'12px',fontWeight:700,color:'rgba(232,244,248,0.8)'}}>{ag.id} — {ag.name}</div>
                  <div style={{fontSize:'9px',color:'rgba(232,244,248,0.3)',fontFamily:"'JetBrains Mono',monospace"}}>Last: {ag.last} · Uptime: {ag.uptime}</div>
                </div>
                <div style={{fontSize:'11px',color:'rgba(232,244,248,0.5)',textAlign:'right',fontFamily:"'JetBrains Mono',monospace"}}>
                  <div style={{fontWeight:700,color:'#00ffc8'}}>{ag.signals}</div>
                  <div style={{fontSize:'9px'}}>items</div>
                </div>
              </div>
            ))}
          </div>

          {/* Live activity */}
          <div style={{background:'rgba(10,22,40,0.7)',border:'1px solid rgba(0,180,216,0.1)',borderRadius:'12px',overflow:'hidden'}}>
            <div style={{padding:'12px 18px',borderBottom:'1px solid rgba(0,255,200,0.06)',display:'flex',justifyContent:'space-between',alignItems:'center',background:'rgba(0,0,0,0.2)'}}>
              <span style={{fontSize:'11px',fontWeight:800,color:'rgba(232,244,248,0.7)',letterSpacing:'0.08em',textTransform:'uppercase',fontFamily:"'Orbitron','Inter',sans-serif"}}>Live Activity</span>
              <span style={{fontSize:'8px',fontWeight:800,padding:'2px 8px',borderRadius:'4px',background:'rgba(0,180,216,0.08)',color:'#00b4d8',letterSpacing:'0.08em',fontFamily:"'JetBrains Mono',monospace"}}>REAL-TIME</span>
            </div>
            <div style={{maxHeight:'320px',overflowY:'auto'}}>
              {ACTIVITY.map(({t,a,type},i)=>(
                <div key={i} style={{padding:'10px 18px',borderBottom:'1px solid rgba(255,255,255,0.025)',display:'flex',gap:'10px',alignItems:'flex-start'}}>
                  <div style={{width:'7px',height:'7px',borderRadius:'50%',background:tc[type]||'#7f8c8d',flexShrink:0,marginTop:'4px',boxShadow:`0 0 4px ${tc[type]||'#7f8c8d'}`}}/>
                  <div style={{flex:1}}>
                    <div style={{fontSize:'12px',color:'rgba(232,244,248,0.65)',lineHeight:1.5}}>{a}</div>
                    <div style={{fontSize:'9px',color:'rgba(232,244,248,0.25)',marginTop:'2px',fontFamily:"'JetBrains Mono',monospace"}}>{t}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Infrastructure */}
        <div style={{background:'rgba(10,22,40,0.7)',border:'1px solid rgba(0,180,216,0.1)',borderRadius:'12px',padding:'18px'}}>
          <div style={{fontSize:'11px',fontWeight:800,color:'rgba(232,244,248,0.5)',letterSpacing:'0.1em',textTransform:'uppercase',marginBottom:'14px',fontFamily:"'Orbitron','Inter',sans-serif"}}>Infrastructure Status</div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'10px'}}>
            {[
              {l:'Frontend (GitHub Pages)',s:'LIVE',v:'fdimonitor.org',c:'#00ffc8'},
              {l:'API (Azure Container)',s:'LIVE',v:'api.fdimonitor.org',c:'#00ffc8'},
              {l:'PostgreSQL (Azure)',s:'DEMO MODE',v:'fdi-db-prod',c:'#ffd700'},
              {l:'Redis Cache (Azure)',s:'LIVE',v:'fdi-cache-prod',c:'#00ffc8'},
            ].map(({l,s,v,c})=>(
              <div key={l} style={{padding:'12px',background:'rgba(255,255,255,0.02)',borderRadius:'10px',border:`1px solid ${c}15`}}>
                <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'4px'}}>
                  <span style={{fontSize:'9px',color:'rgba(232,244,248,0.35)'}}>{l}</span>
                  <span style={{fontSize:'8px',fontWeight:800,padding:'2px 6px',borderRadius:'4px',background:`${c}12`,color:c,letterSpacing:'0.06em'}}>{s}</span>
                </div>
                <div style={{fontSize:'11px',color:'rgba(232,244,248,0.6)',fontFamily:"'JetBrains Mono',monospace"}}>{v}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <Footer/>
    </div>
  );
}
