'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import { Activity, Users, FileText, Zap, TrendingUp, Globe, Bell } from 'lucide-react';

const STATS = [
  {l:'Active Subscribers',v:'12,847',d:'+124 this week',c:'#2ecc71',icon:<Users size={16} color="#2ecc71"/>},
  {l:'Reports Generated',v:'3,241',d:'+48 today',c:'#3498db',icon:<FileText size={16} color="#3498db"/>},
  {l:'Signals Processed',v:'1,847',d:'Last 7 days',c:'#f1c40f',icon:<Zap size={16} color="#f1c40f"/>},
  {l:'Countries Covered',v:'215',d:'Updated weekly',c:'#9b59b6',icon:<Globe size={16} color="#9b59b6"/>},
  {l:'API Calls Today',v:'48,291',d:'+12% vs yesterday',c:'#e67e22',icon:<Activity size={16} color="#e67e22"/>},
  {l:'Newsletter Open Rate',v:'41.2%',d:'+2.1% vs last issue',c:'#2ecc71',icon:<Bell size={16} color="#2ecc71"/>},
];

const AGENT_STATUS = [
  {id:'AGT-01',name:'Data Collection',status:'ACTIVE',last:'2m ago',runs:24,signals:29,uptime:'99.8%'},
  {id:'AGT-02',name:'Signal Detection',status:'ACTIVE',last:'2m ago',runs:24,signals:28,uptime:'99.6%'},
  {id:'AGT-03',name:'Verification',status:'ACTIVE',last:'2m ago',runs:24,signals:28,uptime:'99.4%'},
  {id:'AGT-04',name:'GOSA Scoring',status:'ACTIVE',last:'5m ago',runs:168,signals:15,uptime:'99.9%'},
  {id:'AGT-05',name:'GFR Ranking',status:'ACTIVE',last:'10m ago',runs:168,signals:15,uptime:'99.7%'},
  {id:'AGT-06',name:'Newsletter',status:'PENDING',last:'6d ago',runs:1,signals:1,uptime:'100%'},
];

const RECENT_ACTIVITY = [
  {time:'2m ago',action:'AGT-02 detected PLATINUM signal: Malaysia FDI cap lifted',type:'signal'},
  {time:'8m ago',action:'User trial expired — upgrade prompt triggered (user@devinco.ae)',type:'trial'},
  {time:'14m ago',action:'Report generated: Vietnam EV Battery Analysis (3 pages)',type:'report'},
  {time:'22m ago',action:'New subscriber: m.hassan@misa.gov.sa — Professional trial',type:'user'},
  {time:'31m ago',action:'AGT-04 GOSA update: Singapore +0.3pts, UAE +1.2pts',type:'score'},
  {time:'45m ago',action:'Newsletter Issue #47 generated by AGT-06 — awaiting review',type:'newsletter'},
  {time:'1h ago',action:'API rate limit: 1 user at 94% of daily quota',type:'api'},
  {time:'2h ago',action:'Report downloaded: Thailand EV Analysis (trial user)',type:'report'},
];

export default function AdminPage() {
  const [tick, setTick] = useState(0);
  useEffect(()=>{const iv=setInterval(()=>setTick(t=>t+1),3000);return()=>clearInterval(iv);},[]);

  return (
    <div style={{minHeight:'100vh',background:'#f0f4f8',fontFamily:"Inter,'Helvetica Neue',sans-serif"}}>
      <NavBar/>
      <div style={{background:'linear-gradient(135deg,#0f1e2a,#1a2c3e)',padding:'18px 24px',borderBottom:'1px solid rgba(46,204,113,0.1)'}}>
        <div style={{maxWidth:'1440px',margin:'0 auto',display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:'12px'}}>
          <div>
            <div style={{fontSize:'10px',fontWeight:800,color:'#2ecc71',letterSpacing:'0.12em',marginBottom:'4px'}}>ADMIN DASHBOARD</div>
            <h1 style={{fontSize:'20px',fontWeight:900,color:'white'}}>Platform Operations Center</h1>
          </div>
          <div style={{display:'flex',gap:'8px'}}>
            <Link href="/newsletter" style={{padding:'7px 14px',background:'rgba(46,204,113,0.12)',border:'1px solid rgba(46,204,113,0.25)',borderRadius:'8px',textDecoration:'none',fontSize:'12px',fontWeight:600,color:'#2ecc71'}}>
              Newsletter Admin →
            </Link>
            <button style={{padding:'7px 14px',background:'rgba(255,255,255,0.08)',border:'1px solid rgba(255,255,255,0.15)',borderRadius:'8px',fontSize:'12px',fontWeight:600,color:'rgba(255,255,255,0.8)',fontFamily:'inherit',cursor:'pointer'}}>
              Run All Agents
            </button>
          </div>
        </div>
      </div>

      <div style={{maxWidth:'1440px',margin:'0 auto',padding:'20px 24px'}}>
        {/* Stats grid */}
        <div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:'10px',marginBottom:'16px'}}>
          {STATS.map(({l,v,d,c,icon})=>(
            <div key={l} style={{background:'white',borderRadius:'12px',padding:'16px',border:'1px solid rgba(26,44,62,0.08)',borderTop:`3px solid ${c}`}}>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'8px'}}>
                <span style={{fontSize:'10px',color:'#7f8c8d',textTransform:'uppercase',letterSpacing:'0.05em'}}>{l}</span>
                {icon}
              </div>
              <div style={{fontSize:'22px',fontWeight:900,color:'#1a2c3e',fontFamily:"'JetBrains Mono',monospace"}}>{v}</div>
              <div style={{fontSize:'10px',color:'#7f8c8d',marginTop:'2px'}}>{d}</div>
            </div>
          ))}
        </div>

        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'16px',marginBottom:'16px'}}>
          {/* Agent pipeline status */}
          <div style={{background:'white',borderRadius:'14px',border:'1px solid rgba(26,44,62,0.08)',overflow:'hidden'}}>
            <div style={{padding:'14px 18px',borderBottom:'1px solid rgba(26,44,62,0.06)',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
              <span style={{fontSize:'13px',fontWeight:700,color:'#1a2c3e',display:'flex',alignItems:'center',gap:'6px'}}><Activity size={13} color="#2ecc71"/> AI Agent Pipeline</span>
              <span style={{fontSize:'9px',fontWeight:800,padding:'3px 8px',borderRadius:'8px',background:'rgba(46,204,113,0.1)',color:'#2ecc71'}}>ALL ACTIVE</span>
            </div>
            {AGENT_STATUS.map(ag=>(
              <div key={ag.id} style={{padding:'12px 18px',borderBottom:'1px solid rgba(26,44,62,0.04)',display:'flex',alignItems:'center',gap:'12px'}}>
                <div style={{width:'8px',height:'8px',borderRadius:'50%',background:ag.status==='ACTIVE'?'#2ecc71':'#f1c40f',flexShrink:0,animation:ag.status==='ACTIVE'?'pulse 2s infinite':'none'}}/>
                <div style={{flex:1}}>
                  <div style={{fontSize:'12px',fontWeight:700,color:'#1a2c3e'}}>{ag.id} — {ag.name}</div>
                  <div style={{fontSize:'10px',color:'#7f8c8d'}}>Last run: {ag.last} · Uptime: {ag.uptime}</div>
                </div>
                <div style={{fontSize:'11px',color:'#2c3e50',textAlign:'right'}}>
                  <div style={{fontWeight:700}}>{ag.signals} items</div>
                  <div style={{fontSize:'10px',color:'#7f8c8d'}}>{ag.runs} runs/wk</div>
                </div>
              </div>
            ))}
          </div>

          {/* Live activity feed */}
          <div style={{background:'white',borderRadius:'14px',border:'1px solid rgba(26,44,62,0.08)',overflow:'hidden'}}>
            <div style={{padding:'14px 18px',borderBottom:'1px solid rgba(26,44,62,0.06)',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
              <span style={{fontSize:'13px',fontWeight:700,color:'#1a2c3e',display:'flex',alignItems:'center',gap:'6px'}}><TrendingUp size={13} color="#3498db"/> Live Activity</span>
              <span style={{fontSize:'9px',fontWeight:800,padding:'3px 8px',borderRadius:'8px',background:'rgba(52,152,219,0.1)',color:'#3498db'}}>REAL-TIME</span>
            </div>
            <div style={{maxHeight:'320px',overflowY:'auto'}}>
              {RECENT_ACTIVITY.map(({time,action,type},i)=>{
                const tc: Record<string,string> = {signal:'#2ecc71',trial:'#f1c40f',report:'#3498db',user:'#9b59b6',score:'#e67e22',newsletter:'#2ecc71',api:'#e74c3c'};
                return (
                  <div key={i} style={{padding:'10px 18px',borderBottom:'1px solid rgba(26,44,62,0.04)',display:'flex',gap:'12px',alignItems:'flex-start'}}>
                    <div style={{width:'8px',height:'8px',borderRadius:'50%',background:tc[type]||'#7f8c8d',flexShrink:0,marginTop:'4px'}}/>
                    <div style={{flex:1}}>
                      <div style={{fontSize:'12px',color:'#2c3e50',lineHeight:'1.5'}}>{action}</div>
                      <div style={{fontSize:'10px',color:'#7f8c8d',marginTop:'2px'}}>{time}</div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Infrastructure status */}
        <div style={{background:'white',borderRadius:'14px',border:'1px solid rgba(26,44,62,0.08)',padding:'18px'}}>
          <div style={{fontSize:'13px',fontWeight:700,color:'#1a2c3e',marginBottom:'14px',display:'flex',alignItems:'center',gap:'6px'}}><Globe size={13} color="#2ecc71"/> Infrastructure Status</div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'10px'}}>
            {[
              {l:'Frontend (GitHub Pages)',status:'LIVE',url:'fdimonitor.org',c:'#2ecc71'},
              {l:'API (Azure Container)',status:'LIVE',url:'api.fdimonitor.org',c:'#2ecc71'},
              {l:'PostgreSQL (Azure)',status:'DEMO MODE',url:'fdi-db-prod-fdimahmoud',c:'#f1c40f'},
              {l:'Redis Cache (Azure)',status:'LIVE',url:'fdi-cache-prod.redis',c:'#2ecc71'},
            ].map(({l,status,url,c})=>(
              <div key={l} style={{padding:'12px',background:'rgba(26,44,62,0.02)',borderRadius:'10px',border:'1px solid rgba(26,44,62,0.06)'}}>
                <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'4px'}}>
                  <span style={{fontSize:'10px',color:'#7f8c8d'}}>{l}</span>
                  <span style={{fontSize:'9px',fontWeight:800,padding:'2px 6px',borderRadius:'6px',background:`${c}15`,color:c}}>{status}</span>
                </div>
                <div style={{fontSize:'11px',color:'#2c3e50',fontFamily:"'JetBrains Mono',monospace",wordBreak:'break-all'}}>{url}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}}`}</style>
      <Footer/>
    </div>
  );
}
