/**
 * GFM Export System
 * CSV, JSON, and printable HTML export for all data tables.
 */

export function exportCSV(rows: Record<string,any>[], filename: string) {
  if (!rows.length) return;
  const headers = Object.keys(rows[0]);
  const csv = [
    headers.join(','),
    ...rows.map(r => headers.map(h => {
      const v = r[h];
      const s = String(v ?? '').replace(/"/g, '""');
      return s.includes(',') || s.includes('\n') ? `"${s}"` : s;
    }).join(','))
  ].join('\n');
  downloadBlob(csv, `${filename}.csv`, 'text/csv');
}

export function exportJSON(data: any, filename: string) {
  const json = JSON.stringify(data, null, 2);
  downloadBlob(json, `${filename}.json`, 'application/json');
}

export function exportPrintHTML(title: string, html: string) {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <!DOCTYPE html><html><head>
    <title>${title} — Global FDI Monitor</title>
    <style>
      body{font-family:Arial,sans-serif;max-width:900px;margin:40px auto;color:#1e293b}
      h1{color:#0A2540;border-bottom:2px solid #0A2540;padding-bottom:8px}
      table{width:100%;border-collapse:collapse;margin:20px 0}
      th{background:#0A2540;color:white;padding:8px 12px;text-align:left;font-size:11px;text-transform:uppercase}
      td{padding:8px 12px;border-bottom:1px solid #e2e8f0;font-size:12px}
      tr:nth-child(even){background:#f8fafc}
      .footer{margin-top:40px;font-size:10px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px}
      .badge{display:inline-block;padding:2px 8px;border-radius:9999px;font-size:10px;font-weight:700}
      @media print{body{margin:10px}.no-print{display:none}}
    </style>
    </head><body>
    <h1>${title}</h1>
    <p style="color:#64748b;font-size:12px">Generated by Global FDI Monitor · ${new Date().toLocaleDateString()} · fdimonitor.org</p>
    ${html}
    <div class="footer">
      Global FDI Monitor · fdimonitor.org · © 2026 Forecasta Ltd<br>
      Data sourced from IMF, World Bank, UNCTAD, OECD, IEA. Not financial advice.
    </div>
    </body></html>
  `);
  win.document.close();
  setTimeout(() => win.print(), 500);
}

function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

/** Export GFR table */
export function exportGFR(rankings: any[]) {
  exportCSV(rankings.map(r => ({
    Rank: r.rank, ISO3: r.iso3, Economy: r.name, Region: r.region,
    Income: r.income, Composite: r.composite, Tier: r.tier,
    Macro: r.macro, Policy: r.policy, Digital: r.digital,
    Human: r.human, Infrastructure: r.infra, Sustainability: r.sustain,
    'GDP $B': r.gdp_b, 'FDI Inflows $B': r.fdi_b,
  })), `GFR_Rankings_Q1_2026_${new Date().toISOString().slice(0,10)}`);
}

/** Export signals table */
export function exportSignals(signals: any[]) {
  exportCSV(signals.map(s => ({
    'Reference Code': s.id || s.reference_code,
    Grade: s.grade, Company: s.company, HQ: s.hq,
    Economy: s.economy, 'ISO3': s.iso3,
    'ISIC Sector': s.sector, 'CapEx USD': s.capex_usd,
    'SCI Score': s.sci_score, Type: s.signal_type,
    Status: s.status, Date: s.signal_date,
    'Provenance Source': s.provenance?.source || '',
    'Verified': s.provenance?.verified ? 'Yes' : 'No',
  })), `GFM_Signals_${new Date().toISOString().slice(0,10)}`);
}

/** Export pipeline deals */
export function exportPipeline(deals: any[]) {
  exportCSV(deals.map(d => ({
    ID: d.id, Company: d.company, HQ: d.hq,
    Economy: d.economy || d.iso3, Sector: d.sector,
    'CapEx $M': d.capex_m, Stage: d.stage,
    'Probability %': d.probability, Contact: d.contact,
    'Days in Stage': d.days_in_stage, Notes: d.notes,
  })), `GFM_Pipeline_${new Date().toISOString().slice(0,10)}`);
}
