name: Trigger auto deployment for fdi-backend-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fdi-backend-api-AutoDeployTrigger-8a37cbc9-4ccf-4a56-b067-5c1e48dafe06.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FDIBACKENDAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FDIBACKENDAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FDIBACKENDAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}apps/api
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fdimonitorregistry.azurecr.io
          registryUsername: ${{ secrets.FDIBACKENDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FDIBACKENDAPI_REGISTRY_PASSWORD }}
          containerAppName: fdi-backend-api
          resourceGroup: fdi-monitor-prod
          imageToBuild: fdimonitorregistry.azurecr.io/fdi-backend-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


